import {
  isRetryable,
  isThrottlingError,
  isTransientError,
} from "@distilled.cloud/aws/Category";
import {
  capped,
  jittered,
  Retry,
  type Factory as RetryFactory,
} from "@distilled.cloud/aws/Retry";
import * as Duration from "effect/Duration";
import * as Effect from "effect/Effect";
import { pipe } from "effect/Function";
import * as Layer from "effect/Layer";
import * as Ref from "effect/Ref";
import * as Schedule from "effect/Schedule";
import * as HttpClientError from "effect/unstable/http/HttpClientError";
import { CredentialsStoreLive } from "../Auth/Credentials.ts";
import { Command, CommandProvider } from "../Build/Command.ts";
import * as Provider from "../Provider.ts";
import { KeyPair, KeyPairProvider } from "../KeyPair.ts";
import { Random, RandomProvider } from "../Random.ts";
import * as ACM from "./ACM/index.ts";
import * as ApiGateway from "./ApiGateway/index.ts";
import * as Assets from "./Assets.ts";
import { AwsAuth } from "./AuthProvider.ts";
import * as AutoScaling from "./AutoScaling/index.ts";
import * as CloudFront from "./CloudFront/index.ts";
import * as CloudWatch from "./CloudWatch/index.ts";
import * as Credentials from "./Credentials.ts";
import * as DynamoDB from "./DynamoDB/index.ts";
import * as EC2 from "./EC2/index.ts";
import * as ECR from "./ECR/index.ts";
import * as ECS from "./ECS/index.ts";
import * as EKS from "./EKS/index.ts";
import * as ELBv2 from "./ELBv2/index.ts";
import * as Endpoint from "./Endpoint.ts";
import { Default as DefaultEnvironment } from "./Environment.ts";
import * as EventBridge from "./EventBridge/index.ts";
import * as IAM from "./IAM/index.ts";
import * as IdentityCenter from "./IdentityCenter/index.ts";
import * as Kinesis from "./Kinesis/index.ts";
import * as Lambda from "./Lambda/index.ts";
import * as Logs from "./Logs/index.ts";
import * as Organizations from "./Organizations/index.ts";
import * as RDS from "./RDS/index.ts";
import * as RDSData from "./RDSData/index.ts";
import * as Region from "./Region.ts";
import * as Route53 from "./Route53/index.ts";
import * as S3 from "./S3/index.ts";
import * as Scheduler from "./Scheduler/index.ts";
import * as SecretsManager from "./SecretsManager/index.ts";
import * as SNS from "./SNS/index.ts";
import * as SQS from "./SQS/index.ts";
import * as Website from "./Website/index.ts";

export class Providers extends Provider.ProviderCollection<Providers>()(
  "AWS",
) {}

export const providers = () =>
  Layer.effect(
    Providers,
    Provider.collection([
      Command,
      KeyPair,
      Random,
      ACM.Certificate,
      ApiGateway.Account,
      ApiGateway.ApiKey,
      ApiGateway.Authorizer,
      ApiGateway.BasePathMapping,
      ApiGateway.DeploymentResource,
      ApiGateway.DomainName,
      ApiGateway.GatewayResponse,
      ApiGateway.MethodResource,
      ApiGateway.GatewayResource,
      ApiGateway.RestApi,
      ApiGateway.StageResource,
      ApiGateway.UsagePlan,
      ApiGateway.UsagePlanKey,
      ApiGateway.VpcLink,
      AutoScaling.AutoScalingGroup,
      AutoScaling.LaunchTemplate,
      AutoScaling.ScalingPolicy,
      CloudFront.CachePolicy,
      CloudFront.Distribution,
      CloudFront.Function,
      CloudFront.Invalidation,
      CloudFront.KeyGroup,
      CloudFront.KeyValueStore,
      CloudFront.KvEntries,
      CloudFront.KvRoutesUpdate,
      CloudFront.OriginAccessControl,
      CloudFront.OriginRequestPolicy,
      CloudFront.PublicKey,
      CloudFront.ResponseHeadersPolicy,
      CloudWatch.Alarm,
      CloudWatch.AlarmMuteRule,
      CloudWatch.AnomalyDetector,
      CloudWatch.CompositeAlarm,
      CloudWatch.Dashboard,
      CloudWatch.DescribeAlarmContributorsPolicy,
      CloudWatch.DescribeAlarmHistoryPolicy,
      CloudWatch.DescribeAlarmsForMetricPolicy,
      CloudWatch.DescribeAlarmsPolicy,
      CloudWatch.DescribeAnomalyDetectorsPolicy,
      CloudWatch.DescribeInsightRulesPolicy,
      CloudWatch.DisableAlarmActionsPolicy,
      CloudWatch.DisableInsightRulesPolicy,
      CloudWatch.EnableAlarmActionsPolicy,
      CloudWatch.GetAlarmMuteRulePolicy,
      CloudWatch.GetDashboardPolicy,
      CloudWatch.GetInsightRuleReportPolicy,
      CloudWatch.GetMetricDataPolicy,
      CloudWatch.GetMetricStatisticsPolicy,
      CloudWatch.GetMetricStreamPolicy,
      CloudWatch.GetMetricWidgetImagePolicy,
      CloudWatch.InsightRule,
      CloudWatch.ListAlarmMuteRulesPolicy,
      CloudWatch.ListDashboardsPolicy,
      CloudWatch.ListManagedInsightRulesPolicy,
      CloudWatch.ListMetricsPolicy,
      CloudWatch.ListMetricStreamsPolicy,
      CloudWatch.ListTagsForResourcePolicy,
      CloudWatch.MetricStream,
      CloudWatch.PutMetricDataPolicy,
      CloudWatch.SetAlarmStatePolicy,
      DynamoDB.BatchExecuteStatementPolicy,
      DynamoDB.BatchGetItemPolicy,
      DynamoDB.BatchWriteItemPolicy,
      DynamoDB.DeleteItemPolicy,
      DynamoDB.DescribeTablePolicy,
      DynamoDB.DescribeTimeToLivePolicy,
      DynamoDB.ExecuteStatementPolicy,
      DynamoDB.ExecuteTransactionPolicy,
      DynamoDB.GetItemPolicy,
      DynamoDB.ListTablesPolicy,
      DynamoDB.ListTagsOfResourcePolicy,
      DynamoDB.PutItemPolicy,
      DynamoDB.QueryPolicy,
      DynamoDB.RestoreTableToPointInTimePolicy,
      DynamoDB.ScanPolicy,
      DynamoDB.Table,
      DynamoDB.TransactGetItemsPolicy,
      DynamoDB.TransactWriteItemsPolicy,
      DynamoDB.UpdateItemPolicy,
      DynamoDB.UpdateTimeToLivePolicy,
      EC2.EgressOnlyInternetGateway,
      EC2.EIP,
      EC2.Instance,
      EC2.InternetGateway,
      EC2.NatGateway,
      EC2.NetworkAcl,
      EC2.NetworkAclAssociation,
      EC2.NetworkAclEntry,
      EC2.Route,
      EC2.RouteTable,
      EC2.RouteTableAssociation,
      EC2.SecurityGroup,
      EC2.SecurityGroupRule,
      EC2.Subnet,
      EC2.Vpc,
      EC2.VpcEndpoint,
      ECR.Repository,
      ECS.CapacityProvider,
      ECS.Cluster,
      ECS.DescribeTasksPolicy,
      ECS.ListTasksPolicy,
      ECS.RunTaskPolicy,
      ECS.Service,
      ECS.StopTaskPolicy,
      ECS.Task,
      EKS.AccessEntry,
      EKS.Addon,
      EKS.Cluster,
      EKS.PodIdentityAssociation,
      ELBv2.Listener,
      ELBv2.LoadBalancer,
      ELBv2.TargetGroup,
      EventBridge.DescribeEventBusPolicy,
      EventBridge.DescribeRulePolicy,
      EventBridge.EventBus,
      EventBridge.ListEventBusesPolicy,
      EventBridge.ListRulesPolicy,
      EventBridge.ListTargetsByRulePolicy,
      EventBridge.Permission,
      EventBridge.PutEventsPolicy,
      EventBridge.Rule,
      EventBridge.TestEventPatternPolicy,
      EventBridge.ToLambdaPolicy,
      EventBridge.ToQueuePolicy,
      IAM.AccessKey,
      IAM.AccountAlias,
      IAM.AccountPasswordPolicy,
      IAM.Group,
      IAM.GroupMembership,
      IAM.InstanceProfile,
      IAM.LoginProfile,
      IAM.OpenIDConnectProvider,
      IAM.Policy,
      IAM.Role,
      IAM.SAMLProvider,
      IAM.ServerCertificate,
      IAM.ServiceSpecificCredential,
      IAM.SigningCertificate,
      IAM.SSHPublicKey,
      IAM.User,
      IAM.VirtualMFADevice,
      IdentityCenter.AccountAssignment,
      IdentityCenter.Group,
      IdentityCenter.Instance,
      IdentityCenter.PermissionSet,
      Kinesis.DescribeAccountSettingsPolicy,
      Kinesis.DescribeLimitsPolicy,
      Kinesis.DescribeStreamConsumerPolicy,
      Kinesis.DescribeStreamPolicy,
      Kinesis.DescribeStreamSummaryPolicy,
      Kinesis.GetRecordsPolicy,
      Kinesis.GetResourcePolicyPolicy,
      Kinesis.GetShardIteratorPolicy,
      Kinesis.ListShardsPolicy,
      Kinesis.ListStreamConsumersPolicy,
      Kinesis.ListStreamsPolicy,
      Kinesis.ListTagsForResourcePolicy,
      Kinesis.PutRecordPolicy,
      Kinesis.PutRecordsPolicy,
      Kinesis.Stream,
      Kinesis.StreamConsumer,
      Kinesis.StreamSinkPolicy,
      Kinesis.SubscribeToShardPolicy,
      Lambda.BucketEventSourcePolicy,
      Lambda.EventSourcePolicy,
      Lambda.EventSourceMapping,
      Lambda.Function,
      Lambda.InvokeFunctionPolicy,
      Lambda.Permission,
      Lambda.QueueEventSourcePolicy,
      Lambda.StreamEventSourcePolicy,
      Lambda.TableEventSourcePolicy,
      Lambda.TopicEventSourcePolicy,
      Logs.LogGroup,
      Organizations.Account,
      Organizations.DelegatedAdministrator,
      Organizations.Organization,
      Organizations.OrganizationalUnit,
      Organizations.OrganizationResourcePolicy,
      Organizations.Policy,
      Organizations.PolicyAttachment,
      Organizations.Root,
      Organizations.RootPolicyType,
      Organizations.TrustedServiceAccess,
      RDS.ConnectPolicy,
      RDS.DBCluster,
      RDS.DBClusterEndpoint,
      RDS.DBClusterParameterGroup,
      RDS.DBInstance,
      RDS.DBParameterGroup,
      RDS.DBProxy,
      RDS.DBProxyEndpoint,
      RDS.DBProxyTargetGroup,
      RDS.DBSubnetGroup,
      RDSData.BatchExecuteStatementPolicy,
      RDSData.BeginTransactionPolicy,
      RDSData.CommitTransactionPolicy,
      RDSData.ExecuteSqlPolicy,
      RDSData.ExecuteStatementPolicy,
      RDSData.RollbackTransactionPolicy,
      Route53.Record,
      S3.AbortMultipartUploadPolicy,
      S3.Bucket,
      S3.CompleteMultipartUploadPolicy,
      S3.CreateMultipartUploadPolicy,
      S3.DeleteObjectPolicy,
      S3.GetObjectPolicy,
      S3.HeadObjectPolicy,
      S3.ListObjectsV2Policy,
      S3.PutObjectPolicy,
      S3.CopyObjectPolicy,
      S3.UploadPartPolicy,
      Scheduler.Schedule,
      Scheduler.ScheduleGroup,
      SecretsManager.DescribeSecretPolicy,
      SecretsManager.GetRandomPasswordPolicy,
      SecretsManager.GetSecretValuePolicy,
      SecretsManager.ListSecretsPolicy,
      SecretsManager.PutSecretValuePolicy,
      SecretsManager.Secret,
      SNS.AddPermissionPolicy,
      SNS.ConfirmSubscriptionPolicy,
      SNS.GetDataProtectionPolicyPolicy,
      SNS.GetSubscriptionAttributesPolicy,
      SNS.GetTopicAttributesPolicy,
      SNS.ListSubscriptionsByTopicPolicy,
      SNS.ListSubscriptionsPolicy,
      SNS.ListTagsForResourcePolicy,
      SNS.ListTopicsPolicy,
      SNS.PublishBatchPolicy,
      SNS.PublishPolicy,
      SNS.PutDataProtectionPolicyPolicy,
      SNS.RemovePermissionPolicy,
      SNS.SetSubscriptionAttributesPolicy,
      SNS.SetTopicAttributesPolicy,
      SNS.Subscription,
      SNS.TagResourcePolicy,
      SNS.Topic,
      SNS.TopicSinkPolicy,
      SNS.UntagResourcePolicy,
      SQS.DeleteMessagePolicy,
      SQS.DeleteMessageBatchPolicy,
      SQS.Queue,
      SQS.QueueSinkPolicy,
      SQS.ReceiveMessagePolicy,
      SQS.SendMessageBatchPolicy,
      SQS.SendMessagePolicy,
      Website.AssetDeployment,
    ]),
  ).pipe(
    Layer.provide(
      Layer.mergeAll(
        ACM.CertificateProvider(),
        ApiGateway.AccountProvider(),
        ApiGateway.ApiKeyProvider(),
        ApiGateway.AuthorizerProvider(),
        ApiGateway.BasePathMappingProvider(),
        ApiGateway.DeploymentProvider(),
        ApiGateway.DomainNameProvider(),
        ApiGateway.GatewayResponseProvider(),
        ApiGateway.MethodProvider(),
        ApiGateway.ResourceProvider(),
        ApiGateway.RestApiProvider(),
        ApiGateway.StageProvider(),
        ApiGateway.UsagePlanProvider(),
        ApiGateway.UsagePlanKeyProvider(),
        ApiGateway.VpcLinkProvider(),
        AutoScaling.AutoScalingGroupProvider(),
        AutoScaling.LaunchTemplateProvider(),
        AutoScaling.ScalingPolicyProvider(),
        CloudFront.CachePolicyProvider(),
        CloudFront.DistributionProvider(),
        CloudFront.FunctionProvider(),
        CloudFront.InvalidationProvider(),
        CloudFront.KeyGroupProvider(),
        CloudFront.KeyValueStoreProvider(),
        CloudFront.KvEntriesProvider(),
        CloudFront.KvRoutesUpdateProvider(),
        CloudFront.OriginAccessControlProvider(),
        CloudFront.OriginRequestPolicyProvider(),
        CloudFront.PublicKeyProvider(),
        CloudFront.ResponseHeadersPolicyProvider(),
        CloudWatch.AlarmMuteRuleProvider(),
        CloudWatch.AlarmProvider(),
        CloudWatch.AnomalyDetectorProvider(),
        CloudWatch.CompositeAlarmProvider(),
        CloudWatch.DashboardProvider(),
        CloudWatch.DescribeAlarmContributorsPolicyLive,
        CloudWatch.DescribeAlarmHistoryPolicyLive,
        CloudWatch.DescribeAlarmsForMetricPolicyLive,
        CloudWatch.DescribeAlarmsPolicyLive,
        CloudWatch.DescribeAnomalyDetectorsPolicyLive,
        CloudWatch.DescribeInsightRulesPolicyLive,
        CloudWatch.DisableAlarmActionsPolicyLive,
        CloudWatch.DisableInsightRulesPolicyLive,
        CloudWatch.EnableAlarmActionsPolicyLive,
        CloudWatch.GetAlarmMuteRulePolicyLive,
        CloudWatch.GetDashboardPolicyLive,
        CloudWatch.GetInsightRuleReportPolicyLive,
        CloudWatch.GetMetricDataPolicyLive,
        CloudWatch.GetMetricStatisticsPolicyLive,
        CloudWatch.GetMetricStreamPolicyLive,
        CloudWatch.GetMetricWidgetImagePolicyLive,
        CloudWatch.InsightRuleProvider(),
        CloudWatch.ListAlarmMuteRulesPolicyLive,
        CloudWatch.ListDashboardsPolicyLive,
        CloudWatch.ListManagedInsightRulesPolicyLive,
        CloudWatch.ListMetricsPolicyLive,
        CloudWatch.ListMetricStreamsPolicyLive,
        CloudWatch.ListTagsForResourcePolicyLive,
        CloudWatch.MetricStreamProvider(),
        CloudWatch.PutMetricDataPolicyLive,
        CloudWatch.SetAlarmStatePolicyLive,
        DynamoDB.BatchExecuteStatementPolicyLive,
        DynamoDB.BatchGetItemPolicyLive,
        DynamoDB.BatchWriteItemPolicyLive,
        DynamoDB.DeleteItemPolicyLive,
        DynamoDB.DescribeTablePolicyLive,
        DynamoDB.DescribeTimeToLivePolicyLive,
        DynamoDB.ExecuteStatementPolicyLive,
        DynamoDB.ExecuteTransactionPolicyLive,
        DynamoDB.GetItemPolicyLive,
        DynamoDB.ListTablesPolicyLive,
        DynamoDB.ListTagsOfResourcePolicyLive,
        DynamoDB.PutItemPolicyLive,
        DynamoDB.QueryPolicyLive,
        DynamoDB.RestoreTableToPointInTimePolicyLive,
        DynamoDB.ScanPolicyLive,
        DynamoDB.TableProvider(),
        DynamoDB.TransactGetItemsPolicyLive,
        DynamoDB.TransactWriteItemsPolicyLive,
        DynamoDB.UpdateItemPolicyLive,
        DynamoDB.UpdateTimeToLivePolicyLive,
        EC2.EgressOnlyInternetGatewayProvider(),
        EC2.EIPProvider(),
        EC2.InstanceProvider(),
        EC2.InternetGatewayProvider(),
        EC2.NatGatewayProvider(),
        EC2.NetworkAclAssociationProvider(),
        EC2.NetworkAclEntryProvider(),
        EC2.NetworkAclProvider(),
        EC2.RouteProvider(),
        EC2.RouteTableAssociationProvider(),
        EC2.RouteTableProvider(),
        EC2.SecurityGroupProvider(),
        EC2.SecurityGroupRuleProvider(),
        EC2.SubnetProvider(),
        EC2.VpcEndpointProvider(),
        EC2.VpcProvider(),
        ECR.RepositoryProvider(),
        ECS.CapacityProviderProvider(),
        ECS.ClusterProvider(),
        ECS.DescribeTasksPolicyLive,
        ECS.ListTasksPolicyLive,
        ECS.RunTaskPolicyLive,
        ECS.ServiceProvider(),
        ECS.StopTaskPolicyLive,
        ECS.TaskProvider(),
        EKS.AccessEntryProvider(),
        EKS.AddonProvider(),
        EKS.ClusterProvider(),
        EKS.PodIdentityAssociationProvider(),
        ELBv2.ListenerProvider(),
        ELBv2.LoadBalancerProvider(),
        ELBv2.TargetGroupProvider(),
        EventBridge.DescribeEventBusPolicyLive,
        EventBridge.DescribeRulePolicyLive,
        EventBridge.EventBusProvider(),
        EventBridge.ListEventBusesPolicyLive,
        EventBridge.ListRulesPolicyLive,
        EventBridge.ListTargetsByRulePolicyLive,
        EventBridge.PermissionProvider(),
        EventBridge.PutEventsPolicyLive,
        EventBridge.RuleProvider(),
        EventBridge.TestEventPatternPolicyLive,
        EventBridge.ToLambdaPolicyLive,
        EventBridge.ToQueuePolicyLive,
        IAM.AccessKeyProvider(),
        IAM.AccountAliasProvider(),
        IAM.AccountPasswordPolicyProvider(),
        IAM.GroupMembershipProvider(),
        IAM.GroupProvider(),
        IAM.InstanceProfileProvider(),
        IAM.LoginProfileProvider(),
        IAM.OpenIDConnectProviderProvider(),
        IAM.PolicyProvider(),
        IAM.RoleProvider(),
        IAM.SAMLProviderProvider(),
        IAM.ServerCertificateProvider(),
        IAM.ServiceSpecificCredentialProvider(),
        IAM.SigningCertificateProvider(),
        IAM.SSHPublicKeyProvider(),
        IAM.UserProvider(),
        IAM.VirtualMFADeviceProvider(),
        IdentityCenter.AccountAssignmentProvider(),
        IdentityCenter.GroupProvider(),
        IdentityCenter.InstanceProvider(),
        IdentityCenter.PermissionSetProvider(),
        Kinesis.DescribeAccountSettingsPolicyLive,
        Kinesis.DescribeLimitsPolicyLive,
        Kinesis.DescribeStreamConsumerPolicyLive,
        Kinesis.DescribeStreamPolicyLive,
        Kinesis.DescribeStreamSummaryPolicyLive,
        Kinesis.GetRecordsPolicyLive,
        Kinesis.GetResourcePolicyPolicyLive,
        Kinesis.GetShardIteratorPolicyLive,
        Kinesis.ListShardsPolicyLive,
        Kinesis.ListStreamConsumersPolicyLive,
        Kinesis.ListStreamsPolicyLive,
        Kinesis.ListTagsForResourcePolicyLive,
        Kinesis.PutRecordPolicyLive,
        Kinesis.PutRecordsPolicyLive,
        Kinesis.StreamConsumerProvider(),
        Kinesis.StreamProvider(),
        Kinesis.StreamSinkPolicyLive,
        Kinesis.SubscribeToShardPolicyLive,
        Lambda.BucketEventSourcePolicyLive,
        Lambda.EventSourceMappingProvider(),
        Lambda.EventSourcePolicyLive,
        Lambda.FunctionProvider(),
        Lambda.InvokeFunctionPolicyLive,
        Lambda.PermissionProvider(),
        Lambda.QueueEventSourcePolicyLive,
        Lambda.StreamEventSourcePolicyLive,
        Lambda.TableEventSourcePolicyLive,
        Lambda.TopicEventSourcePolicyLive,
        Logs.LogGroupProvider(),
        Organizations.AccountProvider(),
        Organizations.DelegatedAdministratorProvider(),
        Organizations.OrganizationalUnitProvider(),
        Organizations.OrganizationProvider(),
        Organizations.OrganizationResourcePolicyProvider(),
        Organizations.PolicyAttachmentProvider(),
        Organizations.PolicyProvider(),
        Organizations.RootPolicyTypeProvider(),
        Organizations.RootProvider(),
        Organizations.TrustedServiceAccessProvider(),
        RDS.ConnectPolicyLive,
        RDS.DBClusterEndpointProvider(),
        RDS.DBClusterParameterGroupProvider(),
        RDS.DBClusterProvider(),
        RDS.DBInstanceProvider(),
        RDS.DBParameterGroupProvider(),
        RDS.DBProxyEndpointProvider(),
        RDS.DBProxyProvider(),
        RDS.DBProxyTargetGroupProvider(),
        RDS.DBSubnetGroupProvider(),
        RDSData.BatchExecuteStatementPolicyLive,
        RDSData.BeginTransactionPolicyLive,
        RDSData.CommitTransactionPolicyLive,
        RDSData.ExecuteSqlPolicyLive,
        RDSData.ExecuteStatementPolicyLive,
        RDSData.RollbackTransactionPolicyLive,
        Route53.RecordProvider(),
        S3.AbortMultipartUploadPolicyLive,
        S3.BucketProvider(),
        S3.CompleteMultipartUploadPolicyLive,
        S3.CopyObjectPolicyLive,
        S3.CreateMultipartUploadPolicyLive,
        S3.DeleteObjectPolicyLive,
        S3.GetObjectPolicyLive,
        S3.HeadObjectPolicyLive,
        S3.ListObjectsV2PolicyLive,
        S3.PutObjectPolicyLive,
        S3.UploadPartPolicyLive,
        Scheduler.ScheduleGroupProvider(),
        Scheduler.ScheduleProvider(),
        SecretsManager.DescribeSecretPolicyLive,
        SecretsManager.GetRandomPasswordPolicyLive,
        SecretsManager.GetSecretValuePolicyLive,
        SecretsManager.ListSecretsPolicyLive,
        SecretsManager.PutSecretValuePolicyLive,
        SecretsManager.SecretProvider(),
        SNS.AddPermissionPolicyLive,
        SNS.ConfirmSubscriptionPolicyLive,
        SNS.GetDataProtectionPolicyPolicyLive,
        SNS.GetSubscriptionAttributesPolicyLive,
        SNS.GetTopicAttributesPolicyLive,
        SNS.ListSubscriptionsByTopicPolicyLive,
        SNS.ListSubscriptionsPolicyLive,
        SNS.ListTagsForResourcePolicyLive,
        SNS.ListTopicsPolicyLive,
        SNS.PublishBatchPolicyLive,
        SNS.PublishPolicyLive,
        SNS.PutDataProtectionPolicyPolicyLive,
        SNS.RemovePermissionPolicyLive,
        SNS.SetSubscriptionAttributesPolicyLive,
        SNS.SetTopicAttributesPolicyLive,
        SNS.SubscriptionProvider(),
        SNS.TagResourcePolicyLive,
        SNS.TopicProvider(),
        SNS.TopicSinkPolicyLive,
        SNS.UntagResourcePolicyLive,
        SQS.DeleteMessageBatchPolicyLive,
        SQS.DeleteMessagePolicyLive,
        SQS.QueueProvider(),
        SQS.QueueSinkPolicyLive,
        SQS.ReceiveMessagePolicyLive,
        SQS.SendMessageBatchPolicyLive,
        SQS.SendMessagePolicyLive,
        Website.AssetDeploymentProvider(),
      ),
    ),
    Layer.provideMerge(
      Layer.mergeAll(
        CommandProvider(),
        KeyPairProvider(),
        RandomProvider(),
        Assets.AssetsProvider(),
      ),
    ),
    Layer.provideMerge(Region.fromEnvironment),
    Layer.provideMerge(Credentials.fromEnvironment),
    Layer.provideMerge(Endpoint.fromEnvironment),
    Layer.provideMerge(DefaultEnvironment),
    Layer.provideMerge(AwsAuth),
    Layer.provideMerge(CredentialsStoreLive),
    // Apply a blanket retry policy to every AWS SDK call. Like distilled's
    // `makeDefault` it retries throttling, 5xx, and Smithy `@retryable`
    // errors with exponential backoff + jitter + `RetryAfter` header
    // awareness, but with a higher attempt cap (10 vs 5) so heavy
    // parallel deploys ride out S3 `SlowDown` bursts that span more than
    // a few seconds. Bounded so real rate-limit pressure still surfaces
    // instead of masking as an indefinite hang.
    Layer.provideMerge(Layer.succeed(Retry, awsRetryFactory)),
    Layer.orDie,
  );

// TODO(sam): remove this once it's upstreamed to distilled
const isHttpTransportError = (error: unknown): boolean => {
  if (!HttpClientError.isHttpClientError(error)) return false;
  const tag = error.reason._tag;
  if (tag === "TransportError") return true;
  if (
    tag === "StatusCodeError" &&
    "response" in error.reason &&
    error.reason.response.status >= 500
  ) {
    return true;
  }
  return false;
};

const awsRetryFactory: RetryFactory = (lastError) => ({
  while: (error) =>
    isTransientError(error) ||
    isThrottlingError(error) ||
    isRetryable(error) ||
    isHttpTransportError(error),
  schedule: pipe(
    Schedule.exponential(Duration.millis(200), 2),
    Schedule.modifyDelay(
      Effect.fnUntraced(function* (duration) {
        const error = yield* Ref.get(lastError);
        if (isThrottlingError(error)) {
          // Throttling: floor at 500ms (matches distilled default).
          if (Duration.toMillis(duration) < 500) {
            return Duration.toMillis(Duration.millis(500));
          }
        }
        return Duration.toMillis(duration);
      }),
    ),
    capped(Duration.seconds(5)),
    jittered,
    Schedule.both(Schedule.recurs(10)),
  ),
});
