import type { RemoteWorkspaceBridgeConfig } from "../../../remote-workspace-bridge/remoteWorkspaceBridge.ts";

function renderConfig(input: RemoteWorkspaceBridgeConfig): string {
  return JSON.stringify(
    {
      ...(input.cwd ? { cwd: input.cwd } : {}),
      destination: input.destination,
      transportArgs: [...input.transportArgs],
    },
    null,
    2,
  );
}

function renderRuntimeSource(input: RemoteWorkspaceBridgeConfig): string {
  const config = renderConfig(input);
  return [
    'import { spawn } from "node:child_process";',
    "",
    `const CONFIG = ${config} as const;`,
    "const DEFAULT_READ_LIMIT = 250;",
    "const DEFAULT_GREP_LIMIT = 250;",
    "const DEFAULT_GLOB_LIMIT = 250;",
    "const DEFAULT_LIST_LIMIT = 250;",
    "const MAX_BASH_OUTPUT_CHARS = 64 * 1024;",
    "const REMOTE_EXEC_SCRIPT =",
    '  \'if [ -n "$1" ]; then cd "$1" || exit 1; fi; shift; while [ "$#" -gt 0 ] && [ "$1" != "--" ]; do export "$1"; shift; done; shift; exec "$@"\';',
    "",
    "function shellEscapePosix(argument: string): string {",
    "  return `'${argument.replaceAll(\"'\", `'\\\\''`)}'`;",
    "}",
    "",
    "function normalizeOutput(text: string): string {",
    '  return text.replace(/\\r\\n/g, "\\n").replace(/\\r/g, "\\n");',
    "}",
    "",
    "function truncateOutput(text: string, maxChars: number): string {",
    "  return text.length > maxChars",
    "    ? `${text.slice(0, maxChars)}\\n\\n[output truncated after ${maxChars} characters]`",
    "    : text;",
    "}",
    "",
    "function buildRemoteInvocation(command: string, args: ReadonlyArray<string>): {",
    "  readonly command: string;",
    "  readonly args: ReadonlyArray<string>;",
    "} {",
    "  const remoteCommand = [",
    '    "sh",',
    '    "-lc",',
    "    REMOTE_EXEC_SCRIPT,",
    '    "sh",',
    '    CONFIG.cwd ?? "",',
    '    "--",',
    "    command,",
    "    ...args,",
    "  ]",
    "    .map(shellEscapePosix)",
    '    .join(" ");',
    "",
    "  return {",
    '    command: "ssh",',
    "    args: [...CONFIG.transportArgs, CONFIG.destination, remoteCommand],",
    "  };",
    "}",
    "",
    "async function execRemote(",
    "  command: string,",
    "  args: ReadonlyArray<string>,",
    "  options?: {",
    "    readonly stdin?: string;",
    "    readonly timeoutMs?: number;",
    "    readonly signal?: AbortSignal;",
    "    readonly allowNonZeroExit?: boolean;",
    "  },",
    "): Promise<{ readonly stdout: string; readonly stderr: string; readonly exitCode: number }> {",
    "  const invocation = buildRemoteInvocation(command, args);",
    "  return new Promise((resolve, reject) => {",
    "    const child = spawn(invocation.command, [...invocation.args], {",
    '      stdio: ["pipe", "pipe", "pipe"],',
    "    });",
    '    let stdout = "";',
    '    let stderr = "";',
    "    let settled = false;",
    "    let timedOut = false;",
    "    let timeoutHandle: ReturnType<typeof setTimeout> | undefined;",
    "    let killHandle: ReturnType<typeof setTimeout> | undefined;",
    "",
    "    const cleanup = () => {",
    "      if (timeoutHandle) clearTimeout(timeoutHandle);",
    "      if (killHandle) clearTimeout(killHandle);",
    '      options?.signal?.removeEventListener("abort", onAbort);',
    "    };",
    "",
    "    const settle = (fn: () => void) => {",
    "      if (settled) return;",
    "      settled = true;",
    "      cleanup();",
    "      fn();",
    "    };",
    "",
    "    const onAbort = () => {",
    '      child.kill("SIGTERM");',
    '      settle(() => reject(new Error("Operation aborted")));',
    "    };",
    "",
    "    if (options?.signal?.aborted) {",
    '      settle(() => reject(new Error("Operation aborted")));',
    "      return;",
    "    }",
    "",
    '    options?.signal?.addEventListener("abort", onAbort, { once: true });',
    "",
    "    if (options?.timeoutMs && options.timeoutMs > 0) {",
    "      timeoutHandle = setTimeout(() => {",
    "        timedOut = true;",
    '        child.kill("SIGTERM");',
    "        killHandle = setTimeout(() => {",
    '          child.kill("SIGKILL");',
    "        }, 1_000);",
    "      }, options.timeoutMs);",
    "    }",
    "",
    '    child.stdout.setEncoding("utf8");',
    '    child.stderr.setEncoding("utf8");',
    '    child.stdout.on("data", (chunk: string) => {',
    "      stdout += chunk;",
    "    });",
    '    child.stderr.on("data", (chunk: string) => {',
    "      stderr += chunk;",
    "    });",
    '    child.once("error", (error) => {',
    "      settle(() => reject(error));",
    "    });",
    '    child.once("close", (code) => {',
    "      if (timedOut) {",
    "        settle(() => reject(new Error(`Command timed out after ${Math.floor((options?.timeoutMs ?? 0) / 1000)}s.`)));",
    "        return;",
    "      }",
    "      if (!options?.allowNonZeroExit && code && code !== 0) {",
    "        const detail = normalizeOutput(`${stdout}${stderr}`.trim());",
    "        settle(() => reject(new Error(detail || `Remote command failed with exit code ${code}.`)));",
    "        return;",
    "      }",
    "      settle(() =>",
    "        resolve({ stdout: normalizeOutput(stdout), stderr: normalizeOutput(stderr), exitCode: code ?? 0 }),",
    "      );",
    "    });",
    "",
    "    if (options?.stdin !== undefined) {",
    "      child.stdin.end(options.stdin);",
    "    } else {",
    "      child.stdin.end();",
    "    }",
    "  });",
    "}",
    "",
    'function detectLineEnding(text: string): "\\r\\n" | "\\n" {',
    '  return text.includes("\\r\\n") ? "\\r\\n" : "\\n";',
    "}",
    "",
    "function stripBom(text: string): { readonly bom: string; readonly text: string } {",
    '  return text.startsWith("\\uFEFF") ? { bom: "\\uFEFF", text: text.slice(1) } : { bom: "", text };',
    "}",
    "",
    "function normalizeToLf(text: string): string {",
    '  return text.replace(/\\r\\n/g, "\\n").replace(/\\r/g, "\\n");',
    "}",
    "",
    'function restoreLineEndings(text: string, lineEnding: "\\r\\n" | "\\n"): string {',
    '  return lineEnding === "\\r\\n" ? text.replace(/\\n/g, "\\r\\n") : text;',
    "}",
    "",
    "export function applyEditsToContent(",
    "  rawContent: string,",
    "  edits: ReadonlyArray<{ readonly oldText: string; readonly newText: string }>,",
    "  path: string,",
    "): string {",
    "  if (edits.length === 0) {",
    '    throw new Error("Edit input is invalid. Provide at least one replacement.");',
    "  }",
    "  const { bom, text } = stripBom(rawContent);",
    "  const lineEnding = detectLineEnding(text);",
    "  const normalizedContent = normalizeToLf(text);",
    "  const matches = edits.map((edit, index) => {",
    "    const oldText = normalizeToLf(edit.oldText);",
    "    const newText = normalizeToLf(edit.newText);",
    "    if (oldText.length === 0) {",
    "      throw new Error(`Edit ${index + 1} in ${path} has an empty oldText.`);",
    "    }",
    "    const start = normalizedContent.indexOf(oldText);",
    "    if (start === -1) {",
    "      throw new Error(`Could not find edit ${index + 1} oldText in ${path}.`);",
    "    }",
    "    const duplicate = normalizedContent.indexOf(oldText, start + 1);",
    "    if (duplicate !== -1) {",
    "      throw new Error(`Edit ${index + 1} oldText is not unique in ${path}.`);",
    "    }",
    "    return { start, end: start + oldText.length, newText };",
    "  });",
    "  matches.sort((left, right) => left.start - right.start);",
    "  for (let index = 1; index < matches.length; index += 1) {",
    "    if ((matches[index - 1]?.end ?? 0) > (matches[index]?.start ?? 0)) {",
    "      throw new Error(`Edit replacements overlap in ${path}.`);",
    "    }",
    "  }",
    '  let nextContent = "";',
    "  let cursor = 0;",
    "  for (const match of matches) {",
    "    nextContent += normalizedContent.slice(cursor, match.start);",
    "    nextContent += match.newText;",
    "    cursor = match.end;",
    "  }",
    "  nextContent += normalizedContent.slice(cursor);",
    "  return bom + restoreLineEndings(nextContent, lineEnding);",
    "}",
    "",
    "export async function readRemoteFileContents(path: string, signal?: AbortSignal): Promise<string> {",
    "  const script = [",
    '    "set -eu",',
    '    "target=$1",',
    '    \'if [ ! -e "$target" ]; then printf "Path not found: %s\\\\n" "$target" >&2; exit 1; fi\',',
    '    \'if [ ! -f "$target" ]; then printf "Not a file: %s\\\\n" "$target" >&2; exit 1; fi\',',
    "    'cat \"$target\"',",
    '  ].join("\\n");',
    "  const result = await execRemote('sh', ['-lc', script, 'bigbud-opencode-read-full', path], { signal });",
    "  return result.stdout;",
    "}",
    "",
    "export async function readRemoteFile(path: string, offset?: number, limit?: number, signal?: AbortSignal): Promise<string> {",
    "  const start = Math.max(1, offset ?? 1);",
    "  const effectiveLimit = Math.max(1, Math.min(limit ?? DEFAULT_READ_LIMIT, DEFAULT_READ_LIMIT));",
    "  const end = start + effectiveLimit - 1;",
    "  const marker = '__BIGBUD_TOTAL_LINES__';",
    "  const script = [",
    '    "set -eu",',
    '    "target=$1",',
    '    \'if [ ! -e "$target" ]; then printf "Path not found: %s\\\\n" "$target" >&2; exit 1; fi\',',
    '    \'if [ ! -f "$target" ]; then printf "Not a file: %s\\\\n" "$target" >&2; exit 1; fi\',',
    '    `total_lines=$(awk "END { print NR }" "$target")`,',
    '    `printf "__BIGBUD_TOTAL_LINES__%s\\\\n" "$total_lines" >&2`,',
    '    `sed -n "${start},${end}p" "$target"`,',
    '  ].join("\\n");',
    "  const result = await execRemote('sh', ['-lc', script, 'bigbud-opencode-read', path], { signal });",
    "  const totalLine = result.stderr.split('\\n').find((line) => line.startsWith(marker));",
    "  const totalLines = totalLine ? Number(totalLine.slice(marker.length)) : Number.NaN;",
    "  let output = result.stdout.replace(/\\n$/, '');",
    "  if (output.length === 0) output = '[empty file]';",
    "  if (!Number.isNaN(totalLines) && end < totalLines) {",
    "    output += `\\n\\n[Showing lines ${start}-${end} of ${totalLines}. Use offset=${end + 1} to continue.]`;",
    "  }",
    "  return output;",
    "}",
    "",
    "export async function writeRemoteFile(path: string, content: string, signal?: AbortSignal): Promise<string> {",
    "  const script = [",
    '    "set -eu",',
    '    "target=$1",',
    '    \'mkdir -p "$(dirname "$target")"\',',
    "    'cat > \"$target\"',",
    '  ].join("\\n");',
    "  await execRemote('sh', ['-lc', script, 'bigbud-opencode-write', path], { stdin: content, signal });",
    "  return `Wrote ${path}`;",
    "}",
    "",
    "export async function runRemoteBash(command: string, signal?: AbortSignal): Promise<string> {",
    "  const result = await execRemote('sh', ['-lc', command], { signal, allowNonZeroExit: true });",
    "  const output = truncateOutput(`${result.stdout}${result.stderr}`.trim(), MAX_BASH_OUTPUT_CHARS);",
    "  return output.length > 0 ? output : `[command exited with code ${result.exitCode}]`;",
    "}",
    "",
    "export async function runRemoteGrep(pattern: string, searchPath?: string, signal?: AbortSignal): Promise<string> {",
    "  const root = searchPath && searchPath.length > 0 ? searchPath : (CONFIG.cwd ?? '.');",
    "  const command = `if command -v rg >/dev/null 2>&1; then rg -n --no-heading --color never --max-count ${DEFAULT_GREP_LIMIT} -- ${shellEscapePosix(pattern)} ${shellEscapePosix(root)}; else grep -R -n -- ${shellEscapePosix(pattern)} ${shellEscapePosix(root)} | head -n ${DEFAULT_GREP_LIMIT}; fi`;",
    "  const result = await execRemote('sh', ['-lc', command], { signal, allowNonZeroExit: true });",
    "  const output = `${result.stdout}${result.stderr}`.trim();",
    "  return output.length > 0 ? output : '[no matches]';",
    "}",
    "",
    "export async function runRemoteGlob(pattern: string, searchPath?: string, signal?: AbortSignal): Promise<string> {",
    "  const root = searchPath && searchPath.length > 0 ? searchPath : (CONFIG.cwd ?? '.');",
    '  const command = `if ! command -v rg >/dev/null 2>&1; then printf "ripgrep is required for glob on the remote host.\\n" >&2; exit 1; fi; cd ${shellEscapePosix(root)} && rg --files -g ${shellEscapePosix(pattern)} | head -n ${DEFAULT_GLOB_LIMIT}`;',
    "  const result = await execRemote('sh', ['-lc', command], { signal });",
    "  const output = result.stdout.trim();",
    "  return output.length > 0 ? output : '[no matches]';",
    "}",
    "",
    "export async function runRemoteList(searchPath?: string, signal?: AbortSignal): Promise<string> {",
    "  const root = searchPath && searchPath.length > 0 ? searchPath : (CONFIG.cwd ?? '.');",
    "  const command = `find ${shellEscapePosix(root)} -mindepth 1 -maxdepth 1 | sort | head -n ${DEFAULT_LIST_LIMIT}`;",
    "  const result = await execRemote('sh', ['-lc', command], { signal, allowNonZeroExit: true });",
    "  const output = result.stdout.trim();",
    "  return output.length > 0 ? output : '[empty directory]';",
    "}",
    "",
    "export async function applyRemotePatch(patch: string, signal?: AbortSignal): Promise<string> {",
    "  const command = [",
    '    "set -eu",',
    "    'if command -v git >/dev/null 2>&1; then git apply --whitespace=nowarn - || patch -p0 -N; else patch -p0 -N; fi',",
    '  ].join("\\n");',
    "  await execRemote('sh', ['-lc', command], { stdin: patch, signal });",
    '  return "Applied patch";',
    "}",
  ].join("\n");
}

function renderToolSource(input: {
  readonly description: string;
  readonly argsSource: string;
  readonly executeBody: ReadonlyArray<string>;
}): string {
  return [
    'import { tool } from "@opencode-ai/plugin";',
    'import * as runtime from "../../.bigbud/opencode-remote-runtime.ts";',
    "",
    "export default tool({",
    `  description: ${JSON.stringify(input.description)},`,
    "  args: {",
    input.argsSource,
    "  },",
    "  async execute(args) {",
    ...input.executeBody.map((line) => `    ${line}`),
    "  },",
    "});",
  ].join("\n");
}

export function renderOpencodeRemoteWorkspaceBridgeFiles(
  input: RemoteWorkspaceBridgeConfig,
): Record<string, string> {
  return {
    ".bigbud/opencode-remote-runtime.ts": renderRuntimeSource(input),
    ".opencode/tools/read.ts": renderToolSource({
      description:
        "Read a file from the remote workspace over SSH. Supports relative and absolute paths and optional line pagination.",
      argsSource: [
        '    path: tool.schema.string().describe("Remote file path to read"),',
        '    offset: tool.schema.number().int().positive().optional().describe("1-indexed line offset"),',
        '    limit: tool.schema.number().int().positive().optional().describe("Maximum number of lines to read"),',
      ].join("\n"),
      executeBody: ["return runtime.readRemoteFile(args.path, args.offset, args.limit);"],
    }),
    ".opencode/tools/write.ts": renderToolSource({
      description: "Write or overwrite a file in the remote workspace over SSH.",
      argsSource: [
        '    path: tool.schema.string().describe("Remote file path to write"),',
        '    content: tool.schema.string().describe("Full file contents"),',
      ].join("\n"),
      executeBody: ["return runtime.writeRemoteFile(args.path, args.content);"],
    }),
    ".opencode/tools/edit.ts": renderToolSource({
      description:
        "Apply one or more exact-string edits to a file in the remote workspace over SSH.",
      argsSource: [
        '    path: tool.schema.string().describe("Remote file path to edit"),',
        '    oldText: tool.schema.string().optional().describe("Existing text to replace when performing a single edit"),',
        '    newText: tool.schema.string().optional().describe("Replacement text for a single edit"),',
        "    edits: tool.schema",
        "      .array(",
        "        tool.schema.object({",
        '          oldText: tool.schema.string().describe("Existing text to replace"),',
        '          newText: tool.schema.string().describe("Replacement text"),',
        "        }),",
        "      )",
        '      .optional().describe("Batch edits to apply in order"),',
      ].join("\n"),
      executeBody: [
        "const edits = args.edits ?? (args.oldText !== undefined && args.newText !== undefined",
        "  ? [{ oldText: args.oldText, newText: args.newText }]",
        "  : []);",
        "if (edits.length === 0) {",
        "  throw new Error('Provide either edits[] or both oldText and newText.');",
        "}",
        "const current = await runtime.readRemoteFileContents(args.path);",
        "const next = runtime.applyEditsToContent(current, edits, args.path);",
        "return runtime.writeRemoteFile(args.path, next);",
      ],
    }),
    ".opencode/tools/bash.ts": renderToolSource({
      description: "Run a shell command in the remote workspace over SSH and return stdout/stderr.",
      argsSource: [
        '    command: tool.schema.string().describe("Shell command to execute remotely"),',
      ].join("\n"),
      executeBody: ["return runtime.runRemoteBash(args.command);"],
    }),
    ".opencode/tools/grep.ts": renderToolSource({
      description: "Search the remote workspace using ripgrep over SSH.",
      argsSource: [
        '    pattern: tool.schema.string().describe("Text or regex pattern to search for"),',
        '    path: tool.schema.string().optional().describe("Optional remote directory or file to search within"),',
      ].join("\n"),
      executeBody: ["return runtime.runRemoteGrep(args.pattern, args.path);"],
    }),
    ".opencode/tools/glob.ts": renderToolSource({
      description: "List remote workspace files matching a glob pattern over SSH.",
      argsSource: [
        '    pattern: tool.schema.string().describe("Glob pattern, for example **/*.ts"),',
        '    path: tool.schema.string().optional().describe("Optional remote directory to search from"),',
      ].join("\n"),
      executeBody: ["return runtime.runRemoteGlob(args.pattern, args.path);"],
    }),
    ".opencode/tools/list.ts": renderToolSource({
      description: "List a remote directory over SSH.",
      argsSource: [
        '    path: tool.schema.string().optional().describe("Remote directory to list"),',
      ].join("\n"),
      executeBody: ["return runtime.runRemoteList(args.path);"],
    }),
    ".opencode/tools/apply_patch.ts": renderToolSource({
      description: "Apply a unified diff patch to the remote workspace over SSH.",
      argsSource: ['    patch: tool.schema.string().describe("Unified diff patch contents"),'].join(
        "\n",
      ),
      executeBody: ["return runtime.applyRemotePatch(args.patch);"],
    }),
  };
}
