import type { ThreadOrchestrationHttpConfig } from "../../../orchestration-tools/threadOrchestrationBridge.shared.ts";
import { renderCallOrchestrationToolSource } from "../../../orchestration-tools/threadOrchestrationBridge.shared.ts";

import { renderConfig } from "./OpencodeRemoteWorkspaceBridge.template.helpers.ts";

export function renderRuntimeSource(input: ThreadOrchestrationHttpConfig): string {
  const config = renderConfig(input);
  return [
    `const CONFIG = ${config} as const;`,
    "const DEFAULT_READ_LIMIT = 250;",
    "const DEFAULT_GREP_LIMIT = 250;",
    "const DEFAULT_GLOB_LIMIT = 250;",
    "const DEFAULT_LIST_LIMIT = 250;",
    "const MAX_BASH_OUTPUT_CHARS = 64 * 1024;",
    "function shellEscapePosix(argument: string): string {",
    "  return `'${argument.replaceAll(\"'\", `'\\''`)}'`;",
    "}",
    "",
    "function normalizeOutput(text: string): string {",
    '  return text.replace(/\\r\\n/g, "\\n").replace(/\\r/g, "\\n");',
    "}",
    "",
    "function truncateOutput(text: string, maxChars: number): string {",
    "  return text.length > maxChars",
    "    ? `${text.slice(0, maxChars)}\\n\\n[output truncated after ${maxChars} characters]`",
    "    : text;",
    "}",
    "",
    renderCallOrchestrationToolSource(),
    "",
    "async function execRemote(",
    "  command: string,",
    "  args: ReadonlyArray<string>,",
    "  options?: {",
    "    readonly stdin?: string;",
    "    readonly timeoutMs?: number;",
    "    readonly signal?: AbortSignal;",
    "    readonly allowNonZeroExit?: boolean;",
    "  },",
    "): Promise<{ readonly stdout: string; readonly stderr: string; readonly exitCode: number }> {",
    "  const response = await callOrchestrationTool({",
    "    action: 'remote_workspace_process',",
    "    remoteCommand: command,",
    "    remoteArgs: args,",
    "    ...(options?.stdin !== undefined ? { remoteStdin: options.stdin } : {}),",
    "    remoteAllowNonZeroExit: options?.allowNonZeroExit === true,",
    "    remoteTimeoutMs: options?.timeoutMs ?? 30_000,",
    "    remoteMaxOutputBytes: 1024 * 1024,",
    "    remoteOutputMode: 'truncate',",
    "  }, options?.signal);",
    "  const result = response.result ?? {};",
    "  return {",
    "    stdout: normalizeOutput(String(result.stdout ?? '')),",
    "    stderr: normalizeOutput(String(result.stderr ?? '')),",
    "    exitCode: Number.isInteger(result.code) ? result.code : 0,",
    "  };",
    "}",
    "",
    'function detectLineEnding(text: string): "\\r\\n" | "\\n" {',
    '  return text.includes("\\r\\n") ? "\\r\\n" : "\\n";',
    "}",
    "",
    "function stripBom(text: string): { readonly bom: string; readonly text: string } {",
    '  return text.startsWith("\\uFEFF") ? { bom: "\\uFEFF", text: text.slice(1) } : { bom: "", text };',
    "}",
    "",
    "function normalizeToLf(text: string): string {",
    '  return text.replace(/\\r\\n/g, "\\n").replace(/\\r/g, "\\n");',
    "}",
    "",
    'function restoreLineEndings(text: string, lineEnding: "\\r\\n" | "\\n"): string {',
    '  return lineEnding === "\\r\\n" ? text.replace(/\\n/g, "\\r\\n") : text;',
    "}",
    "",
    "export function applyEditsToContent(",
    "  rawContent: string,",
    "  edits: ReadonlyArray<{ readonly oldText: string; readonly newText: string }>,",
    "  path: string,",
    "): string {",
    "  if (edits.length === 0) {",
    '    throw new Error("Edit input is invalid. Provide at least one replacement.");',
    "  }",
    "  const { bom, text } = stripBom(rawContent);",
    "  const lineEnding = detectLineEnding(text);",
    "  const normalizedContent = normalizeToLf(text);",
    "  const matches = edits.map((edit, index) => {",
    "    const oldText = normalizeToLf(edit.oldText);",
    "    const newText = normalizeToLf(edit.newText);",
    "    if (oldText.length === 0) {",
    "      throw new Error(`Edit ${index + 1} in ${path} has an empty oldText.`);",
    "    }",
    "    const start = normalizedContent.indexOf(oldText);",
    "    if (start === -1) {",
    "      throw new Error(`Could not find edit ${index + 1} oldText in ${path}.`);",
    "    }",
    "    const duplicate = normalizedContent.indexOf(oldText, start + 1);",
    "    if (duplicate !== -1) {",
    "      throw new Error(`Edit ${index + 1} oldText is not unique in ${path}.`);",
    "    }",
    "    return { start, end: start + oldText.length, newText };",
    "  });",
    "  matches.sort((left, right) => left.start - right.start);",
    "  for (let index = 1; index < matches.length; index += 1) {",
    "    if ((matches[index - 1]?.end ?? 0) > (matches[index]?.start ?? 0)) {",
    "      throw new Error(`Edit replacements overlap in ${path}.`);",
    "    }",
    "  }",
    '  let nextContent = "";',
    "  let cursor = 0;",
    "  for (const match of matches) {",
    "    nextContent += normalizedContent.slice(cursor, match.start);",
    "    nextContent += match.newText;",
    "    cursor = match.end;",
    "  }",
    "  nextContent += normalizedContent.slice(cursor);",
    "  return bom + restoreLineEndings(nextContent, lineEnding);",
    "}",
    "",
    "export async function readRemoteFileContents(path: string, signal?: AbortSignal): Promise<string> {",
    "  const script = [",
    '    "set -eu",',
    '    "target=$1",',
    '    \'if [ ! -e "$target" ]; then printf "Path not found: %s\\n" "$target" >&2; exit 1; fi\',',
    '    \'if [ ! -f "$target" ]; then printf "Not a file: %s\\n" "$target" >&2; exit 1; fi\',',
    "    'cat \"$target\"',",
    '  ].join("\\n");',
    "  const result = await execRemote('sh', ['-lc', script, 'bigbud-opencode-read-full', path], { signal });",
    "  return result.stdout;",
    "}",
    "",
    "export async function readRemoteFile(path: string, offset?: number, limit?: number, signal?: AbortSignal): Promise<string> {",
    "  const start = Math.max(1, offset ?? 1);",
    "  const effectiveLimit = Math.max(1, Math.min(limit ?? DEFAULT_READ_LIMIT, DEFAULT_READ_LIMIT));",
    "  const end = start + effectiveLimit - 1;",
    "  const marker = '__BIGBUD_TOTAL_LINES__';",
    "  const script = [",
    '    "set -eu",',
    '    "target=$1",',
    '    \'if [ ! -e "$target" ]; then printf "Path not found: %s\\n" "$target" >&2; exit 1; fi\',',
    '    \'if [ ! -f "$target" ]; then printf "Not a file: %s\\n" "$target" >&2; exit 1; fi\',',
    '    `total_lines=$(awk "END { print NR }" "$target")`,',
    '    `printf "__BIGBUD_TOTAL_LINES__%s\\n" "$total_lines" >&2`,',
    '    `sed -n "${start},${end}p" "$target"`,',
    '  ].join("\\n");',
    "  const result = await execRemote('sh', ['-lc', script, 'bigbud-opencode-read', path], { signal });",
    "  const totalLine = result.stderr.split('\\n').find((line) => line.startsWith(marker));",
    "  const totalLines = totalLine ? Number(totalLine.slice(marker.length)) : Number.NaN;",
    "  let output = result.stdout.replace(/\\n$/, '');",
    "  if (output.length === 0) output = '[empty file]';",
    "  if (!Number.isNaN(totalLines) && end < totalLines) {",
    "    output += `\\n\\n[Showing lines ${start}-${end} of ${totalLines}. Use offset=${end + 1} to continue.]`;",
    "  }",
    "  return output;",
    "}",
    "",
    "export async function writeRemoteFile(path: string, content: string, signal?: AbortSignal): Promise<string> {",
    "  const script = [",
    '    "set -eu",',
    '    "target=$1",',
    '    \'mkdir -p "$(dirname "$target")"\',',
    "    'cat > \"$target\"',",
    '  ].join("\\n");',
    "  await execRemote('sh', ['-lc', script, 'bigbud-opencode-write', path], { stdin: content, signal });",
    "  return `Wrote ${path}`;",
    "}",
    "",
    "export async function runRemoteBash(command: string, signal?: AbortSignal): Promise<string> {",
    "  const result = await execRemote('sh', ['-lc', command], { signal, allowNonZeroExit: true });",
    "  const output = truncateOutput(`${result.stdout}${result.stderr}`.trim(), MAX_BASH_OUTPUT_CHARS);",
    "  return output.length > 0 ? output : `[command exited with code ${result.exitCode}]`;",
    "}",
    "",
    "export async function runRemoteGrep(pattern: string, searchPath?: string, signal?: AbortSignal): Promise<string> {",
    "  const root = searchPath && searchPath.length > 0 ? searchPath : '.';",
    "  const command = `if command -v rg >/dev/null 2>&1; then rg -n --no-heading --color never --max-count ${DEFAULT_GREP_LIMIT} -- ${shellEscapePosix(pattern)} ${shellEscapePosix(root)}; else grep -R -n -- ${shellEscapePosix(pattern)} ${shellEscapePosix(root)} | head -n ${DEFAULT_GREP_LIMIT}; fi`;",
    "  const result = await execRemote('sh', ['-lc', command], { signal, allowNonZeroExit: true });",
    "  const output = `${result.stdout}${result.stderr}`.trim();",
    "  return output.length > 0 ? output : '[no matches]';",
    "}",
    "",
    "export async function runRemoteGlob(pattern: string, searchPath?: string, signal?: AbortSignal): Promise<string> {",
    "  const root = searchPath && searchPath.length > 0 ? searchPath : '.';",
    '  const command = `if ! command -v rg >/dev/null 2>&1; then printf "ripgrep is required for glob on the remote host.\\n" >&2; exit 1; fi; cd ${shellEscapePosix(root)} && rg --files -g ${shellEscapePosix(pattern)} | head -n ${DEFAULT_GLOB_LIMIT}`;',
    "  const result = await execRemote('sh', ['-lc', command], { signal });",
    "  const output = result.stdout.trim();",
    "  return output.length > 0 ? output : '[no matches]';",
    "}",
    "",
    "export async function runRemoteList(searchPath?: string, signal?: AbortSignal): Promise<string> {",
    "  const root = searchPath && searchPath.length > 0 ? searchPath : '.';",
    "  const command = `find ${shellEscapePosix(root)} -mindepth 1 -maxdepth 1 | sort | head -n ${DEFAULT_LIST_LIMIT}`;",
    "  const result = await execRemote('sh', ['-lc', command], { signal, allowNonZeroExit: true });",
    "  const output = result.stdout.trim();",
    "  return output.length > 0 ? output : '[empty directory]';",
    "}",
    "",
    "export async function applyRemotePatch(patch: string, signal?: AbortSignal): Promise<string> {",
    "  if (patch.trimStart().startsWith('*** Begin Patch')) {",
    "    throw new Error('OpenCode patch syntax is not a unified diff. Use the remote edit or write tool instead.');",
    "  }",
    "  const command = [",
    '    "set -eu",',
    "    'patch_file=${TMPDIR:-/tmp}/bigbud-opencode-patch-$$',",
    "    'cleanup() { rm -f \"$patch_file\"; }',",
    "    'trap cleanup 0 HUP INT TERM',",
    "    'cat > \"$patch_file\"',",
    '    \'if command -v git >/dev/null 2>&1 && git apply --check --whitespace=nowarn "$patch_file"; then git apply --whitespace=nowarn "$patch_file"; elif command -v patch >/dev/null 2>&1 && patch --dry-run -p0 -N < "$patch_file" >/dev/null; then patch -p0 -N < "$patch_file"; else printf "Patch could not be applied as a unified diff. Use the remote edit or write tool instead.\\n" >&2; exit 1; fi\',',
    '  ].join("\\n");',
    "  await execRemote('sh', ['-lc', command], { stdin: patch, signal });",
    '  return "Applied patch";',
    "}",
  ].join("\n");
}
