import * as RpcGroup from "effect/unstable/rpc/RpcGroup";

import { WS_METHODS } from "../constants/websocket.constant";
import {
  WsKanbanCreateRpc,
  WsKanbanDeleteRpc,
  WsKanbanGetRpc,
  WsKanbanListRpc,
  WsKanbanMoveRpc,
  WsKanbanReorderRpc,
  WsKanbanUpdateRpc,
  WsNotesCreateRpc,
  WsNotesDeleteRpc,
  WsNotesGetRpc,
  WsNotesListRpc,
  WsNotesUpdateRpc,
  WsProjectsListDirectoryRpc,
  WsProjectsReadFilePreviewRpc,
  WsProjectsSearchEntriesRpc,
  WsProjectsSearchFileContentsRpc,
  WsProjectsWriteFileRpc,
  WsSubscribeProjectDirectoryChangesRpc,
  WsTeachListProjectsRpc,
} from "./rpc.workspace";
import {
  WsServerCreateAutomationRpc,
  WsServerDeleteAutomationRpc,
  WsServerGetAutomationRpc,
  WsServerListAllAutomationsRpc,
  WsServerListAutomationRunsRpc,
  WsServerListAutomationsRpc,
  WsServerPauseAutomationRpc,
  WsServerResumeAutomationRpc,
  WsServerTriggerAutomationRpc,
  WsServerUpdateAutomationRpc,
} from "./rpc.automation";
import {
  WsGitCheckoutRpc,
  WsGitCreateBranchRpc,
  WsGitCreateWorktreeRpc,
  WsGitDiscardChangesRpc,
  WsGitFetchRpc,
  WsGitGetCommitDetailsRpc,
  WsGitInitRpc,
  WsGitListBranchesRpc,
  WsGitListCommitsRpc,
  WsGitPreparePullRequestThreadRpc,
  WsGitPullRpc,
  WsGitReadWorkingTreeDiffRpc,
  WsGitRefreshStatusRpc,
  WsGitRemoveWorktreeRpc,
  WsGitResolvePullRequestRpc,
  WsGitRunStackedActionRpc,
  WsServerCreateMobileRemotePairingRpc,
  WsServerExportThreadContextRpc,
  WsServerGetConfigRpc,
  WsServerGetSettingsRpc,
  WsServerListMobileRemoteSessionsRpc,
  WsServerReadDocumentUrlRpc,
  WsServerRefreshProvidersRpc,
  WsServerRevokeMobileRemoteSessionRpc,
  WsServerUnlockSshKeyRpc,
  WsServerUnlockSshPasswordRpc,
  WsServerUpdateSettingsRpc,
  WsServerUpsertKeybindingRpc,
  WsServerVerifyExecutionTargetRpc,
  WsServerWriteHandoffDocumentRpc,
  WsShellOpenInEditorRpc,
  WsShellOpenPathRpc,
  WsSubscribeGitStatusRpc,
  WsTerminalClearRpc,
  WsTerminalCloseRpc,
  WsTerminalOpenRpc,
  WsTerminalResizeRpc,
  WsTerminalRestartRpc,
  WsTerminalWriteRpc,
} from "./rpc.core";
import {
  WsOrchestrationDispatchCommandRpc,
  WsOrchestrationGetFullThreadDiffRpc,
  WsOrchestrationGetSnapshotRpc,
  WsOrchestrationGetTurnDiffRpc,
  WsOrchestrationReplayEventsRpc,
  WsSubscribeOrchestrationDomainEventsRpc,
  WsSubscribeServerConfigRpc,
  WsSubscribeServerLifecycleRpc,
  WsSubscribeTerminalEventsRpc,
  WsSubscribeThinkingActivityDeltasRpc,
} from "./rpc.stream";

export { WS_METHODS };
export * from "./rpc.automation";
export * from "./rpc.core";
export * from "./rpc.stream";
export * from "./rpc.workspace";

export const WsRpcGroup = RpcGroup.make(
  WsServerGetConfigRpc,
  WsServerRefreshProvidersRpc,
  WsServerVerifyExecutionTargetRpc,
  WsServerUnlockSshKeyRpc,
  WsServerUnlockSshPasswordRpc,
  WsServerUpsertKeybindingRpc,
  WsServerGetSettingsRpc,
  WsServerUpdateSettingsRpc,
  WsServerReadDocumentUrlRpc,
  WsServerWriteHandoffDocumentRpc,
  WsServerExportThreadContextRpc,
  WsServerCreateMobileRemotePairingRpc,
  WsServerListMobileRemoteSessionsRpc,
  WsServerRevokeMobileRemoteSessionRpc,
  WsServerGetAutomationRpc,
  WsServerListAllAutomationsRpc,
  WsServerListAutomationsRpc,
  WsServerCreateAutomationRpc,
  WsServerUpdateAutomationRpc,
  WsServerPauseAutomationRpc,
  WsServerResumeAutomationRpc,
  WsServerDeleteAutomationRpc,
  WsServerTriggerAutomationRpc,
  WsServerListAutomationRunsRpc,
  WsProjectsSearchEntriesRpc,
  WsProjectsSearchFileContentsRpc,
  WsProjectsListDirectoryRpc,
  WsSubscribeProjectDirectoryChangesRpc,
  WsProjectsReadFilePreviewRpc,
  WsProjectsWriteFileRpc,
  WsKanbanListRpc,
  WsKanbanGetRpc,
  WsKanbanCreateRpc,
  WsKanbanUpdateRpc,
  WsKanbanDeleteRpc,
  WsKanbanMoveRpc,
  WsKanbanReorderRpc,
  WsNotesListRpc,
  WsNotesGetRpc,
  WsNotesCreateRpc,
  WsNotesUpdateRpc,
  WsNotesDeleteRpc,
  WsTeachListProjectsRpc,
  WsShellOpenInEditorRpc,
  WsShellOpenPathRpc,
  WsSubscribeGitStatusRpc,
  WsGitPullRpc,
  WsGitRefreshStatusRpc,
  WsGitRunStackedActionRpc,
  WsGitResolvePullRequestRpc,
  WsGitPreparePullRequestThreadRpc,
  WsGitListBranchesRpc,
  WsGitListCommitsRpc,
  WsGitGetCommitDetailsRpc,
  WsGitReadWorkingTreeDiffRpc,
  WsGitCreateWorktreeRpc,
  WsGitRemoveWorktreeRpc,
  WsGitCreateBranchRpc,
  WsGitCheckoutRpc,
  WsGitInitRpc,
  WsGitFetchRpc,
  WsGitDiscardChangesRpc,
  WsTerminalOpenRpc,
  WsTerminalWriteRpc,
  WsTerminalResizeRpc,
  WsTerminalClearRpc,
  WsTerminalRestartRpc,
  WsTerminalCloseRpc,
  WsSubscribeOrchestrationDomainEventsRpc,
  WsSubscribeThinkingActivityDeltasRpc,
  WsSubscribeTerminalEventsRpc,
  WsSubscribeServerConfigRpc,
  WsSubscribeServerLifecycleRpc,
  WsOrchestrationGetSnapshotRpc,
  WsOrchestrationDispatchCommandRpc,
  WsOrchestrationGetTurnDiffRpc,
  WsOrchestrationGetFullThreadDiffRpc,
  WsOrchestrationReplayEventsRpc,
);
