import * as RpcGroup from "effect/unstable/rpc/RpcGroup";

import { WS_METHODS } from "../constants/websocket.constant";
import {
  WsKanbanCreateRpc,
  WsKanbanDeleteRpc,
  WsKanbanGetRpc,
  WsKanbanListRpc,
  WsKanbanMoveRpc,
  WsKanbanReorderRpc,
  WsKanbanUpdateRpc,
  WsNotesCreateRpc,
  WsNotesDeleteRpc,
  WsNotesGetRpc,
  WsNotesListRpc,
  WsNotesUpdateRpc,
  WsProjectsListDirectoryRpc,
  WsProjectsReadFilePreviewRpc,
  WsProjectsSearchEntriesRpc,
  WsProjectsSearchFileContentsRpc,
  WsProjectsWriteFileRpc,
  WsSubscribeProjectDirectoryChangesRpc,
  WsTeachListProjectsRpc,
} from "./rpc.workspace";
import {
  WsServerCreateAutomationRpc,
  WsServerCreateOwnedAutomationRpc,
  WsServerDeleteAutomationRpc,
  WsServerGetAutomationRpc,
  WsServerListAllAutomationsRpc,
  WsServerListAutomationRunsRpc,
  WsServerListAutomationsRpc,
  WsServerPauseAutomationRpc,
  WsServerResumeAutomationRpc,
  WsServerTriggerAutomationRpc,
  WsServerUpdateAutomationRpc,
} from "./rpc.automation";
import { WsServerGetUsageSummaryRpc } from "./rpc.usage";
import {
  WsPluginsGetRpc,
  WsPluginsInstallRpc,
  WsPluginsListCatalogRpc,
  WsPluginsRefreshCatalogRpc,
  WsPluginsUninstallRpc,
  WsPluginsUpdateRpc,
} from "./rpc.plugins";
import {
  WsServerPreviewThreadRetentionRpc,
  WsServerSetThreadRetentionPolicyRpc,
  WsServerStartThreadRetentionRpc,
} from "./rpc.retention";
import {
  WsGitCheckoutRpc,
  WsGitCreateBranchRpc,
  WsGitRenameBranchRpc,
  WsGitDeleteBranchRpc,
  WsGitCreateWorktreeRpc,
  WsGitDiscardChangesRpc,
  WsGitFetchRpc,
  WsGitGetCommitDetailsRpc,
  WsGitInitRpc,
  WsGitListBranchesRpc,
  WsGitListCommitsRpc,
  WsGitPreparePullRequestThreadRpc,
  WsGitPullRpc,
  WsGitReadWorkingTreeDiffRpc,
  WsGitRefreshStatusRpc,
  WsGitRemoveWorktreeRpc,
  WsGitResolvePullRequestRpc,
  WsGitRunStackedActionRpc,
  WsServerActivateCliProxyRpc,
  WsServerCreateMobileRemotePairingRpc,
  WsServerExportThreadContextRpc,
  WsServerGetConfigRpc,
  WsServerGetHandoffJobRpc,
  WsServerGetSettingsRpc,
  WsServerInstallRemoteAgentRpc,
  WsServerListMobileRemoteSessionsRpc,
  WsServerPingRpc,
  WsServerReadDocumentUrlRpc,
  WsServerRefreshProvidersRpc,
  WsServerRevokeMobileRemoteSessionRpc,
  WsServerStartHandoffJobRpc,
  WsServerSetThreadPinnedRpc,
  WsServerUnlockSshKeyRpc,
  WsServerUnlockSshPasswordRpc,
  WsServerUpdateSettingsRpc,
  WsServerUpsertKeybindingRpc,
  WsServerVerifyExecutionTargetRpc,
  WsServerWriteHandoffDocumentRpc,
  WsShellOpenInEditorRpc,
  WsShellOpenInTerminalRpc,
  WsShellOpenPathRpc,
  WsSubscribeGitStatusRpc,
  WsTerminalClearRpc,
  WsTerminalCloseRpc,
  WsTerminalOpenRpc,
  WsTerminalResizeRpc,
  WsTerminalRestartRpc,
  WsTerminalWriteRpc,
} from "./rpc.core";
import {
  WsOrchestrationAcknowledgeDeliveryRpc,
  WsOrchestrationAcknowledgeDeliveryBaselineRpc,
  WsOrchestrationDispatchCommandRpc,
  WsOrchestrationGetCommandOutcomeRpc,
  WsOrchestrationGetFullThreadDiffRpc,
  WsOrchestrationGetSnapshotRpc,
  WsOrchestrationGetSidebarThreadCatalogRpc,
  WsOrchestrationGetStartupProjectCatalogRpc,
  WsOrchestrationGetProjectThreadSummariesRpc,
  WsOrchestrationGetSelectedThreadDetailRpc,
  WsOrchestrationGetThreadOwnershipRpc,
  WsOrchestrationGetTurnDiffRpc,
  WsOrchestrationReplayEventsRpc,
  WsSubscribeOrchestrationDomainEventsRpc,
  WsSubscribeServerConfigRpc,
  WsSubscribeServerLifecycleRpc,
  WsSubscribeTerminalEventsRpc,
  WsSubscribeThinkingActivityDeltasRpc,
} from "./rpc.stream";
import {
  WsCompleteVisibleBrowserCommandRpc,
  WsGetVisibleBrowserLeasesRpc,
  WsRevokeVisibleBrowserLeaseRpc,
  WsSubscribeVisibleBrowserCommandsRpc,
} from "./rpc.browser";

export { WS_METHODS };
export * from "./rpc.automation";
export * from "./rpc.browser";
export * from "./rpc.core";
export * from "./rpc.retention";
export * from "./rpc.stream";
export * from "./rpc.usage";
export * from "./plugins";
export * from "./rpc.plugins";
export * from "./rpc.workspace";

export const WsRpcGroup = RpcGroup.make(
  WsPluginsListCatalogRpc,
  WsPluginsGetRpc,
  WsPluginsRefreshCatalogRpc,
  WsPluginsInstallRpc,
  WsPluginsUpdateRpc,
  WsPluginsUninstallRpc,
  WsServerGetConfigRpc,
  WsServerPingRpc,
  WsServerRefreshProvidersRpc,
  WsServerActivateCliProxyRpc,
  WsServerVerifyExecutionTargetRpc,
  WsServerInstallRemoteAgentRpc,
  WsServerUnlockSshKeyRpc,
  WsServerUnlockSshPasswordRpc,
  WsServerUpsertKeybindingRpc,
  WsServerGetSettingsRpc,
  WsServerUpdateSettingsRpc,
  WsServerPreviewThreadRetentionRpc,
  WsServerStartThreadRetentionRpc,
  WsServerSetThreadRetentionPolicyRpc,
  WsServerSetThreadPinnedRpc,
  WsServerReadDocumentUrlRpc,
  WsServerWriteHandoffDocumentRpc,
  WsServerExportThreadContextRpc,
  WsServerStartHandoffJobRpc,
  WsServerGetHandoffJobRpc,
  WsServerCreateMobileRemotePairingRpc,
  WsServerListMobileRemoteSessionsRpc,
  WsServerRevokeMobileRemoteSessionRpc,
  WsServerGetAutomationRpc,
  WsServerListAllAutomationsRpc,
  WsServerListAutomationsRpc,
  WsServerCreateAutomationRpc,
  WsServerCreateOwnedAutomationRpc,
  WsServerUpdateAutomationRpc,
  WsServerPauseAutomationRpc,
  WsServerResumeAutomationRpc,
  WsServerDeleteAutomationRpc,
  WsServerTriggerAutomationRpc,
  WsServerListAutomationRunsRpc,
  WsServerGetUsageSummaryRpc,
  WsProjectsSearchEntriesRpc,
  WsProjectsSearchFileContentsRpc,
  WsProjectsListDirectoryRpc,
  WsSubscribeProjectDirectoryChangesRpc,
  WsProjectsReadFilePreviewRpc,
  WsProjectsWriteFileRpc,
  WsKanbanListRpc,
  WsKanbanGetRpc,
  WsKanbanCreateRpc,
  WsKanbanUpdateRpc,
  WsKanbanDeleteRpc,
  WsKanbanMoveRpc,
  WsKanbanReorderRpc,
  WsNotesListRpc,
  WsNotesGetRpc,
  WsNotesCreateRpc,
  WsNotesUpdateRpc,
  WsNotesDeleteRpc,
  WsTeachListProjectsRpc,
  WsShellOpenInEditorRpc,
  WsShellOpenInTerminalRpc,
  WsShellOpenPathRpc,
  WsSubscribeGitStatusRpc,
  WsGitPullRpc,
  WsGitRefreshStatusRpc,
  WsGitRunStackedActionRpc,
  WsGitResolvePullRequestRpc,
  WsGitPreparePullRequestThreadRpc,
  WsGitListBranchesRpc,
  WsGitListCommitsRpc,
  WsGitGetCommitDetailsRpc,
  WsGitReadWorkingTreeDiffRpc,
  WsGitCreateWorktreeRpc,
  WsGitRemoveWorktreeRpc,
  WsGitCreateBranchRpc,
  WsGitRenameBranchRpc,
  WsGitDeleteBranchRpc,
  WsGitCheckoutRpc,
  WsGitInitRpc,
  WsGitFetchRpc,
  WsGitDiscardChangesRpc,
  WsTerminalOpenRpc,
  WsTerminalWriteRpc,
  WsTerminalResizeRpc,
  WsTerminalClearRpc,
  WsTerminalRestartRpc,
  WsTerminalCloseRpc,
  WsSubscribeOrchestrationDomainEventsRpc,
  WsSubscribeThinkingActivityDeltasRpc,
  WsSubscribeTerminalEventsRpc,
  WsSubscribeServerConfigRpc,
  WsSubscribeServerLifecycleRpc,
  WsSubscribeVisibleBrowserCommandsRpc,
  WsCompleteVisibleBrowserCommandRpc,
  WsRevokeVisibleBrowserLeaseRpc,
  WsGetVisibleBrowserLeasesRpc,
  WsOrchestrationGetSnapshotRpc,
  WsOrchestrationGetSidebarThreadCatalogRpc,
  WsOrchestrationGetStartupProjectCatalogRpc,
  WsOrchestrationGetProjectThreadSummariesRpc,
  WsOrchestrationGetSelectedThreadDetailRpc,
  WsOrchestrationGetThreadOwnershipRpc,
  WsOrchestrationGetCommandOutcomeRpc,
  WsOrchestrationDispatchCommandRpc,
  WsOrchestrationGetTurnDiffRpc,
  WsOrchestrationGetFullThreadDiffRpc,
  WsOrchestrationReplayEventsRpc,
  WsOrchestrationAcknowledgeDeliveryRpc,
  WsOrchestrationAcknowledgeDeliveryBaselineRpc,
);
