import type { ThreadOrchestrationHttpConfig } from "../orchestration-tools/threadOrchestrationBridge.shared.ts";
import { renderCallOrchestrationToolSource } from "../orchestration-tools/threadOrchestrationBridge.shared.ts";
import {
  MCP_SERVER_TEMPLATE_PRELUDE,
  MCP_SERVER_TOOL_DEFINITIONS,
  renderConfig,
} from "./remoteWorkspaceMcpBridge.template.shared.ts";

export function renderRemoteWorkspaceMcpServerSource(input: ThreadOrchestrationHttpConfig): string {
  const config = renderConfig(input);
  return [
    ...MCP_SERVER_TEMPLATE_PRELUDE,
    `const CONFIG = ${config};`,
    ...MCP_SERVER_TOOL_DEFINITIONS,
    "let negotiatedProtocolVersion = DEFAULT_NEGOTIATED_PROTOCOL_VERSION;",
    "let outputFraming = 'content-length';",
    "let stdinBuffer = Buffer.alloc(0);",
    "",
    "function shellEscapePosix(argument) {",
    "  return `'${String(argument).replaceAll(\"'\", `'\\\\''`)}'`;",
    "}",
    "",
    "function normalizeOutput(text) {",
    '  return text.replace(/\\r\\n/g, "\\n").replace(/\\r/g, "\\n");',
    "}",
    "",
    "function truncateOutput(text, maxChars) {",
    "  return text.length > maxChars",
    "    ? `${text.slice(0, maxChars)}\\n\\n[output truncated after ${maxChars} characters]`",
    "    : text;",
    "}",
    "",
    "function textContent(text) {",
    '  return [{ type: "text", text }];',
    "}",
    "",
    "function writeMessage(message) {",
    "  if (outputFraming === 'newline') {",
    "    process.stdout.write(`${JSON.stringify(message)}\\n`);",
    "    return;",
    "  }",
    "  const encoded = Buffer.from(JSON.stringify(message), 'utf8');",
    "  process.stdout.write(`Content-Length: ${encoded.length}\\r\\n\\r\\n`);",
    "  process.stdout.write(encoded);",
    "}",
    "",
    "function writeResponse(id, result) {",
    "  writeMessage({ jsonrpc: JSONRPC_VERSION, id, result });",
    "}",
    "",
    "function writeError(id, code, message) {",
    "  writeMessage({ jsonrpc: JSONRPC_VERSION, id, error: { code, message } });",
    "}",
    "",
    renderCallOrchestrationToolSource(),
    "",
    "async function execRemote(command, args, options = {}) {",
    "  const response = await callOrchestrationTool({",
    "    action: 'remote_workspace_process',",
    "    remoteCommand: command,",
    "    remoteArgs: args,",
    "    ...(options.stdin !== undefined ? { remoteStdin: options.stdin } : {}),",
    "    remoteAllowNonZeroExit: options.allowNonZeroExit === true,",
    "    remoteTimeoutMs: options.timeoutMs ?? 30_000,",
    "    remoteMaxOutputBytes: 1024 * 1024,",
    "    remoteOutputMode: 'truncate',",
    "  }, options.signal);",
    "  const result = response.result ?? {};",
    "  return {",
    "    stdout: normalizeOutput(String(result.stdout ?? '')),",
    "    stderr: normalizeOutput(String(result.stderr ?? '')),",
    "    exitCode: Number.isInteger(result.code) ? result.code : 0,",
    "  };",
    "}",
    "",
    "function detectLineEnding(text) {",
    '  return text.includes("\\r\\n") ? "\\r\\n" : "\\n";',
    "}",
    "",
    "function stripBom(text) {",
    '  return text.startsWith("\\uFEFF") ? { bom: "\\uFEFF", text: text.slice(1) } : { bom: "", text };',
    "}",
    "",
    "function normalizeToLf(text) {",
    '  return text.replace(/\\r\\n/g, "\\n").replace(/\\r/g, "\\n");',
    "}",
    "",
    "function restoreLineEndings(text, lineEnding) {",
    '  return lineEnding === "\\r\\n" ? text.replace(/\\n/g, "\\r\\n") : text;',
    "}",
    "",
    "function applyEditsToContent(rawContent, edits, path) {",
    "  if (edits.length === 0) throw new Error('Edit input is invalid. Provide at least one replacement.');",
    "  const { bom, text } = stripBom(rawContent);",
    "  const lineEnding = detectLineEnding(text);",
    "  const normalizedContent = normalizeToLf(text);",
    "  const matches = edits.map((edit, index) => {",
    "    const oldText = normalizeToLf(edit.oldText);",
    "    const newText = normalizeToLf(edit.newText);",
    "    if (oldText.length === 0) throw new Error(`Edit ${index + 1} in ${path} has an empty oldText.`);",
    "    const start = normalizedContent.indexOf(oldText);",
    "    if (start === -1) throw new Error(`Could not find edit ${index + 1} oldText in ${path}.`);",
    "    const duplicate = normalizedContent.indexOf(oldText, start + 1);",
    "    if (duplicate !== -1) throw new Error(`Edit ${index + 1} oldText is not unique in ${path}.`);",
    "    return { start, end: start + oldText.length, newText };",
    "  });",
    "  matches.sort((left, right) => left.start - right.start);",
    "  for (let index = 1; index < matches.length; index += 1) {",
    "    if ((matches[index - 1]?.end ?? 0) > (matches[index]?.start ?? 0)) {",
    "      throw new Error(`Edit replacements overlap in ${path}.`);",
    "    }",
    "  }",
    '  let nextContent = "";',
    "  let cursor = 0;",
    "  for (const match of matches) {",
    "    nextContent += normalizedContent.slice(cursor, match.start);",
    "    nextContent += match.newText;",
    "    cursor = match.end;",
    "  }",
    "  nextContent += normalizedContent.slice(cursor);",
    "  return bom + restoreLineEndings(nextContent, lineEnding);",
    "}",
    "",
    "async function readRemoteFileContents(path) {",
    '  const script = [\'set -eu\', \'target=$1\', \'if [ ! -e "$target" ]; then printf "Path not found: %s\\\\n" "$target" >&2; exit 1; fi\', \'if [ ! -f "$target" ]; then printf "Not a file: %s\\\\n" "$target" >&2; exit 1; fi\', \'cat "$target"\'].join(\'\\n\');',
    "  const result = await execRemote('sh', ['-lc', script, 'bigbud-mcp-read-full', path]);",
    "  return result.stdout;",
    "}",
    "",
    "async function callTool(name, args) {",
    "  switch (name) {",
    "    case 'read': {",
    "      const start = Math.max(1, Number(args?.offset ?? 1));",
    "      const effectiveLimit = Math.max(1, Math.min(Number(args?.limit ?? DEFAULT_READ_LIMIT), DEFAULT_READ_LIMIT));",
    "      const end = start + effectiveLimit - 1;",
    "      const marker = '__BIGBUD_TOTAL_LINES__';",
    '      const script = [\'set -eu\', \'target=$1\', \'if [ ! -e "$target" ]; then printf "Path not found: %s\\\\n" "$target" >&2; exit 1; fi\', \'if [ ! -f "$target" ]; then printf "Not a file: %s\\\\n" "$target" >&2; exit 1; fi\', \'total_lines=$(awk "END { print NR }" "$target")\', \'printf "__BIGBUD_TOTAL_LINES__%s\\\\n" "$total_lines" >&2\', `sed -n "${start},${end}p" "$target"`].join(\'\\n\');',
    "      const result = await execRemote('sh', ['-lc', script, 'bigbud-mcp-read', String(args?.path ?? '')]);",
    "      const totalLine = result.stderr.split('\\n').find((line) => line.startsWith(marker));",
    "      const totalLines = totalLine ? Number(totalLine.slice(marker.length)) : Number.NaN;",
    "      let output = result.stdout.replace(/\\n$/, '');",
    "      if (output.length === 0) output = '[empty file]';",
    "      if (!Number.isNaN(totalLines) && end < totalLines) output += `\\n\\n[Showing lines ${start}-${end} of ${totalLines}. Use offset=${end + 1} to continue.]`;",
    "      return { content: textContent(output) };",
    "    }",
    "    case 'write': {",
    "      const script = ['set -eu', 'target=$1', 'mkdir -p \"$(dirname \"$target\")\"', 'cat > \"$target\"'].join('\\n');",
    "      await execRemote('sh', ['-lc', script, 'bigbud-mcp-write', String(args?.path ?? '')], { stdin: String(args?.content ?? '') });",
    "      return { content: textContent(`Wrote ${String(args?.path ?? '')}`) };",
    "    }",
    "    case 'edit': {",
    "      const edits = Array.isArray(args?.edits)",
    "        ? args.edits",
    "        : args?.oldText !== undefined && args?.newText !== undefined",
    "          ? [{ oldText: String(args.oldText), newText: String(args.newText) }]",
    "          : [];",
    "      if (edits.length === 0) throw new Error('Provide either edits[] or both oldText and newText.');",
    "      const path = String(args?.path ?? '');",
    "      const current = await readRemoteFileContents(path);",
    "      const next = applyEditsToContent(current, edits, path);",
    "      const script = ['set -eu', 'target=$1', 'mkdir -p \"$(dirname \"$target\")\"', 'cat > \"$target\"'].join('\\n');",
    "      await execRemote('sh', ['-lc', script, 'bigbud-mcp-edit', path], { stdin: next });",
    "      return { content: textContent(`Wrote ${path}`) };",
    "    }",
    "    case 'bash': {",
    "      const result = await execRemote('sh', ['-lc', String(args?.command ?? '')], { allowNonZeroExit: true });",
    "      const output = truncateOutput(`${result.stdout}${result.stderr}`.trim(), MAX_BASH_OUTPUT_CHARS);",
    "      return { content: textContent(output.length > 0 ? output : `[command exited with code ${result.exitCode}]`) };",
    "    }",
    "    case 'grep': {",
    "      const root = args?.path ? String(args.path) : '.';",
    "      const pattern = String(args?.pattern ?? '');",
    "      const command = `if command -v rg >/dev/null 2>&1; then rg -n --no-heading --color never --max-count ${DEFAULT_GREP_LIMIT} -- ${shellEscapePosix(pattern)} ${shellEscapePosix(root)}; else grep -R -n -- ${shellEscapePosix(pattern)} ${shellEscapePosix(root)} | head -n ${DEFAULT_GREP_LIMIT}; fi`;",
    "      const result = await execRemote('sh', ['-lc', command], { allowNonZeroExit: true });",
    "      const output = `${result.stdout}${result.stderr}`.trim();",
    "      return { content: textContent(output.length > 0 ? output : '[no matches]') };",
    "    }",
    "    case 'glob': {",
    "      const root = args?.path ? String(args.path) : '.';",
    "      const pattern = String(args?.pattern ?? '');",
    '      const command = `if ! command -v rg >/dev/null 2>&1; then printf "ripgrep is required for glob on the remote host.\\\\n" >&2; exit 1; fi; cd ${shellEscapePosix(root)} && rg --files -g ${shellEscapePosix(pattern)} | head -n ${DEFAULT_GLOB_LIMIT}`;',
    "      const result = await execRemote('sh', ['-lc', command]);",
    "      const output = result.stdout.trim();",
    "      return { content: textContent(output.length > 0 ? output : '[no matches]') };",
    "    }",
    "    case 'list': {",
    "      const root = args?.path ? String(args.path) : '.';",
    "      const command = `find ${shellEscapePosix(root)} -mindepth 1 -maxdepth 1 | sort | head -n ${DEFAULT_LIST_LIMIT}`;",
    "      const result = await execRemote('sh', ['-lc', command], { allowNonZeroExit: true });",
    "      const output = result.stdout.trim();",
    "      return { content: textContent(output.length > 0 ? output : '[empty directory]') };",
    "    }",
    "    case 'apply_patch': {",
    "      const command = ['set -eu', 'if command -v git >/dev/null 2>&1; then git apply --whitespace=nowarn - || patch -p0 -N; else patch -p0 -N; fi'].join('\\n');",
    "      await execRemote('sh', ['-lc', command], { stdin: String(args?.patch ?? '') });",
    '      return { content: textContent("Applied patch") };',
    "    }",
    "    default:",
    "      throw new Error(`Unknown tool: ${name}`);",
    "  }",
    "}",
    "",
    "async function handleRequest(request) {",
    "  if (request.method === 'initialize') {",
    "    const requestedVersion = request.params?.protocolVersion;",
    "    negotiatedProtocolVersion = SUPPORTED_PROTOCOL_VERSIONS.includes(requestedVersion)",
    "      ? requestedVersion",
    "      : DEFAULT_NEGOTIATED_PROTOCOL_VERSION;",
    "    writeResponse(request.id, {",
    "      protocolVersion: negotiatedProtocolVersion,",
    "      capabilities: { tools: {} },",
    '      serverInfo: { name: "bigbud-remote-workspace", version: "0.1.0" },',
    "      instructions: 'bigbud remote workspace bridge. Commands run through the configured bigbud remote agent.',",
    "    });",
    "    return;",
    "  }",
    "  if (request.method === 'notifications/initialized') return;",
    "  if (request.method === 'ping') { writeResponse(request.id, {}); return; }",
    "  if (request.method === 'tools/list') { writeResponse(request.id, { tools: TOOLS }); return; }",
    "  if (request.method === 'tools/call') {",
    "    try {",
    "      const result = await callTool(String(request.params?.name ?? ''), request.params?.arguments ?? {});",
    "      writeResponse(request.id, result);",
    "    } catch (error) {",
    "      writeResponse(request.id, { content: textContent(error instanceof Error ? error.message : String(error)), isError: true });",
    "    }",
    "    return;",
    "  }",
    "  writeError(request.id ?? null, -32601, `Method not found: ${String(request.method)}`);",
    "}",
    "",
    "function handleJsonPayload(payload, framing) {",
    "  outputFraming = framing;",
    "  let message;",
    "  try { message = JSON.parse(payload); } catch { return; }",
    "  if (!message || typeof message !== 'object' || !('method' in message)) return;",
    "  void handleRequest(message).catch((error) => {",
    "    writeError(message.id ?? null, -32000, error instanceof Error ? error.message : String(error));",
    "  });",
    "}",
    "",
    "process.stdin.on('readable', () => {",
    "  let chunk;",
    "  while ((chunk = process.stdin.read()) !== null) {",
    "    stdinBuffer = Buffer.concat([stdinBuffer, chunk]);",
    "    while (true) {",
    "      const headerEnd = stdinBuffer.indexOf('\\r\\n\\r\\n');",
    "      if (headerEnd === -1) {",
    "        if (/^Content-Length:/i.test(stdinBuffer.toString('utf8', 0, Math.min(stdinBuffer.length, 32)))) break;",
    "        const newlineIndex = stdinBuffer.indexOf('\\n');",
    "        if (newlineIndex === -1) break;",
    "        const line = stdinBuffer.slice(0, newlineIndex).toString('utf8').trim();",
    "        stdinBuffer = stdinBuffer.slice(newlineIndex + 1);",
    "        if (line.length > 0) handleJsonPayload(line, 'newline');",
    "        continue;",
    "      }",
    "      const header = stdinBuffer.slice(0, headerEnd).toString('utf8');",
    "      const match = header.match(/Content-Length:\\s*(\\d+)/i);",
    "      if (!match) { stdinBuffer = stdinBuffer.slice(headerEnd + 4); continue; }",
    "      const contentLength = Number(match[1]);",
    "      const totalLength = headerEnd + 4 + contentLength;",
    "      if (stdinBuffer.length < totalLength) break;",
    "      const body = stdinBuffer.slice(headerEnd + 4, totalLength).toString('utf8');",
    "      stdinBuffer = stdinBuffer.slice(totalLength);",
    "      handleJsonPayload(body, 'content-length');",
    "    }",
    "  }",
    "});",
    "process.stdin.resume();",
  ].join("\n");
}
