import type { ThreadOrchestrationHttpConfig } from "../orchestration-tools/threadOrchestrationBridge.shared.ts";

export function renderConfig(input: ThreadOrchestrationHttpConfig): string {
  return JSON.stringify(input, null, 2);
}

export const MCP_SERVER_TEMPLATE_PRELUDE = [
  'const JSONRPC_VERSION = "2.0";',
  'const DEFAULT_NEGOTIATED_PROTOCOL_VERSION = "2025-03-26";',
  "const SUPPORTED_PROTOCOL_VERSIONS = [",
  '  "2025-11-25",',
  '  "2025-06-18",',
  '  "2025-03-26",',
  '  "2024-11-05",',
  '  "2024-10-07",',
  "];",
  "const DEFAULT_READ_LIMIT = 250;",
  "const DEFAULT_GREP_LIMIT = 250;",
  "const DEFAULT_GLOB_LIMIT = 250;",
  "const DEFAULT_LIST_LIMIT = 250;",
  "const MAX_BASH_OUTPUT_CHARS = 64 * 1024;",
  "",
];

export const MCP_SERVER_TOOL_DEFINITIONS = [
  "const TOOLS = [",
  "  {",
  '    name: "read",',
  '    description: "Read a file from the remote workspace through bigbud. Supports optional line pagination.",',
  "    inputSchema: {",
  '      type: "object",',
  "      properties: {",
  '        path: { type: "string", description: "Remote file path to read" },',
  '        offset: { type: "integer", minimum: 1, description: "1-indexed line offset" },',
  '        limit: { type: "integer", minimum: 1, description: "Maximum number of lines to read" },',
  "      },",
  '      required: ["path"],',
  "      additionalProperties: false,",
  "    },",
  "  },",
  "  {",
  '    name: "write",',
  '    description: "Write or overwrite a file in the remote workspace through bigbud.",',
  "    inputSchema: {",
  '      type: "object",',
  "      properties: {",
  '        path: { type: "string", description: "Remote file path to write" },',
  '        content: { type: "string", description: "Full file contents" },',
  "      },",
  '      required: ["path", "content"],',
  "      additionalProperties: false,",
  "    },",
  "  },",
  "  {",
  '    name: "edit",',
  '    description: "Apply exact-text edits to a file in the remote workspace through bigbud.",',
  "    inputSchema: {",
  '      type: "object",',
  "      properties: {",
  '        path: { type: "string", description: "Remote file path to edit" },',
  '        oldText: { type: "string", description: "Existing text to replace for a single edit" },',
  '        newText: { type: "string", description: "Replacement text for a single edit" },',
  "        edits: {",
  '          type: "array",',
  "          items: {",
  '            type: "object",',
  "            properties: {",
  '              oldText: { type: "string" },',
  '              newText: { type: "string" },',
  "            },",
  '            required: ["oldText", "newText"],',
  "            additionalProperties: false,",
  "          },",
  '          description: "Batch edits to apply in order",',
  "        },",
  "      },",
  '      required: ["path"],',
  "      additionalProperties: false,",
  "    },",
  "  },",
  "  {",
  '    name: "bash",',
  '    description: "Run a shell command in the remote workspace through bigbud and return stdout/stderr.",',
  "    inputSchema: {",
  '      type: "object",',
  "      properties: {",
  '        command: { type: "string", description: "Shell command to execute remotely" },',
  "      },",
  '      required: ["command"],',
  "      additionalProperties: false,",
  "    },",
  "  },",
  "  {",
  '    name: "grep",',
  '    description: "Search the remote workspace using ripgrep through bigbud.",',
  "    inputSchema: {",
  '      type: "object",',
  "      properties: {",
  '        pattern: { type: "string", description: "Text or regex pattern to search for" },',
  '        path: { type: "string", description: "Optional remote directory or file to search within" },',
  "      },",
  '      required: ["pattern"],',
  "      additionalProperties: false,",
  "    },",
  "  },",
  "  {",
  '    name: "glob",',
  '    description: "List remote workspace files matching a glob pattern through bigbud.",',
  "    inputSchema: {",
  '      type: "object",',
  "      properties: {",
  '        pattern: { type: "string", description: "Glob pattern, for example **/*.ts" },',
  '        path: { type: "string", description: "Optional remote directory to search from" },',
  "      },",
  '      required: ["pattern"],',
  "      additionalProperties: false,",
  "    },",
  "  },",
  "  {",
  '    name: "list",',
  '    description: "List a remote directory through bigbud.",',
  "    inputSchema: {",
  '      type: "object",',
  "      properties: {",
  '        path: { type: "string", description: "Remote directory to list" },',
  "      },",
  "      additionalProperties: false,",
  "    },",
  "  },",
  "  {",
  '    name: "apply_patch",',
  '    description: "Apply a unified diff patch to the remote workspace through bigbud.",',
  "    inputSchema: {",
  '      type: "object",',
  "      properties: {",
  '        patch: { type: "string", description: "Unified diff patch contents" },',
  "      },",
  '      required: ["patch"],',
  "      additionalProperties: false,",
  "    },",
  "  },",
  "];",
  "",
];
