import type { RemoteWorkspaceBridgeConfig } from "./remoteWorkspaceBridge.ts";

function renderConfig(input: RemoteWorkspaceBridgeConfig): string {
  return JSON.stringify(
    {
      ...(input.cwd ? { cwd: input.cwd } : {}),
      destination: input.destination,
      transportArgs: [...input.transportArgs],
    },
    null,
    2,
  );
}

export function renderRemoteWorkspaceMcpServerSource(input: RemoteWorkspaceBridgeConfig): string {
  const config = renderConfig(input);
  return [
    'import { spawn } from "node:child_process";',
    "",
    `const CONFIG = ${config};`,
    'const JSONRPC_VERSION = "2.0";',
    'const DEFAULT_NEGOTIATED_PROTOCOL_VERSION = "2025-03-26";',
    "const SUPPORTED_PROTOCOL_VERSIONS = [",
    '  "2025-11-25",',
    '  "2025-06-18",',
    '  "2025-03-26",',
    '  "2024-11-05",',
    '  "2024-10-07",',
    "];",
    "const DEFAULT_READ_LIMIT = 250;",
    "const DEFAULT_GREP_LIMIT = 250;",
    "const DEFAULT_GLOB_LIMIT = 250;",
    "const DEFAULT_LIST_LIMIT = 250;",
    "const MAX_BASH_OUTPUT_CHARS = 64 * 1024;",
    "const REMOTE_EXEC_SCRIPT =",
    '  \'if [ -n "$1" ]; then cd "$1" || exit 1; fi; shift; while [ "$#" -gt 0 ] && [ "$1" != "--" ]; do export "$1"; shift; done; shift; exec "$@"\';',
    "",
    "const TOOLS = [",
    "  {",
    '    name: "read",',
    '    description: "Read a file from the remote workspace over SSH. Supports optional line pagination.",',
    "    inputSchema: {",
    '      type: "object",',
    "      properties: {",
    '        path: { type: "string", description: "Remote file path to read" },',
    '        offset: { type: "integer", minimum: 1, description: "1-indexed line offset" },',
    '        limit: { type: "integer", minimum: 1, description: "Maximum number of lines to read" },',
    "      },",
    '      required: ["path"],',
    "      additionalProperties: false,",
    "    },",
    "  },",
    "  {",
    '    name: "write",',
    '    description: "Write or overwrite a file in the remote workspace over SSH.",',
    "    inputSchema: {",
    '      type: "object",',
    "      properties: {",
    '        path: { type: "string", description: "Remote file path to write" },',
    '        content: { type: "string", description: "Full file contents" },',
    "      },",
    '      required: ["path", "content"],',
    "      additionalProperties: false,",
    "    },",
    "  },",
    "  {",
    '    name: "edit",',
    '    description: "Apply exact-text edits to a file in the remote workspace over SSH.",',
    "    inputSchema: {",
    '      type: "object",',
    "      properties: {",
    '        path: { type: "string", description: "Remote file path to edit" },',
    '        oldText: { type: "string", description: "Existing text to replace for a single edit" },',
    '        newText: { type: "string", description: "Replacement text for a single edit" },',
    "        edits: {",
    '          type: "array",',
    "          items: {",
    '            type: "object",',
    "            properties: {",
    '              oldText: { type: "string" },',
    '              newText: { type: "string" },',
    "            },",
    '            required: ["oldText", "newText"],',
    "            additionalProperties: false,",
    "          },",
    '          description: "Batch edits to apply in order",',
    "        },",
    "      },",
    '      required: ["path"],',
    "      additionalProperties: false,",
    "    },",
    "  },",
    "  {",
    '    name: "bash",',
    '    description: "Run a shell command in the remote workspace over SSH and return stdout/stderr.",',
    "    inputSchema: {",
    '      type: "object",',
    "      properties: {",
    '        command: { type: "string", description: "Shell command to execute remotely" },',
    "      },",
    '      required: ["command"],',
    "      additionalProperties: false,",
    "    },",
    "  },",
    "  {",
    '    name: "grep",',
    '    description: "Search the remote workspace using ripgrep over SSH.",',
    "    inputSchema: {",
    '      type: "object",',
    "      properties: {",
    '        pattern: { type: "string", description: "Text or regex pattern to search for" },',
    '        path: { type: "string", description: "Optional remote directory or file to search within" },',
    "      },",
    '      required: ["pattern"],',
    "      additionalProperties: false,",
    "    },",
    "  },",
    "  {",
    '    name: "glob",',
    '    description: "List remote workspace files matching a glob pattern over SSH.",',
    "    inputSchema: {",
    '      type: "object",',
    "      properties: {",
    '        pattern: { type: "string", description: "Glob pattern, for example **/*.ts" },',
    '        path: { type: "string", description: "Optional remote directory to search from" },',
    "      },",
    '      required: ["pattern"],',
    "      additionalProperties: false,",
    "    },",
    "  },",
    "  {",
    '    name: "list",',
    '    description: "List a remote directory over SSH.",',
    "    inputSchema: {",
    '      type: "object",',
    "      properties: {",
    '        path: { type: "string", description: "Remote directory to list" },',
    "      },",
    "      additionalProperties: false,",
    "    },",
    "  },",
    "  {",
    '    name: "apply_patch",',
    '    description: "Apply a unified diff patch to the remote workspace over SSH.",',
    "    inputSchema: {",
    '      type: "object",',
    "      properties: {",
    '        patch: { type: "string", description: "Unified diff patch contents" },',
    "      },",
    '      required: ["patch"],',
    "      additionalProperties: false,",
    "    },",
    "  },",
    "];",
    "",
    "let negotiatedProtocolVersion = DEFAULT_NEGOTIATED_PROTOCOL_VERSION;",
    "let stdinBuffer = Buffer.alloc(0);",
    "",
    "function shellEscapePosix(argument) {",
    "  return `'${String(argument).replaceAll(\"'\", `'\\\\''`)}'`;",
    "}",
    "",
    "function normalizeOutput(text) {",
    '  return text.replace(/\\r\\n/g, "\\n").replace(/\\r/g, "\\n");',
    "}",
    "",
    "function truncateOutput(text, maxChars) {",
    "  return text.length > maxChars",
    "    ? `${text.slice(0, maxChars)}\\n\\n[output truncated after ${maxChars} characters]`",
    "    : text;",
    "}",
    "",
    "function textContent(text) {",
    '  return [{ type: "text", text }];',
    "}",
    "",
    "function writeMessage(message) {",
    "  const encoded = Buffer.from(JSON.stringify(message), 'utf8');",
    "  process.stdout.write(`Content-Length: ${encoded.length}\\r\\n\\r\\n`);",
    "  process.stdout.write(encoded);",
    "}",
    "",
    "function writeResponse(id, result) {",
    "  writeMessage({ jsonrpc: JSONRPC_VERSION, id, result });",
    "}",
    "",
    "function writeError(id, code, message) {",
    "  writeMessage({ jsonrpc: JSONRPC_VERSION, id, error: { code, message } });",
    "}",
    "",
    "function buildRemoteInvocation(command, args) {",
    "  const remoteCommand = [",
    '    "sh",',
    '    "-lc",',
    "    REMOTE_EXEC_SCRIPT,",
    '    "sh",',
    '    CONFIG.cwd ?? "",',
    '    "--",',
    "    command,",
    "    ...args,",
    "  ].map(shellEscapePosix).join(' ');",
    '  return { command: "ssh", args: [...CONFIG.transportArgs, CONFIG.destination, remoteCommand] };',
    "}",
    "",
    "async function execRemote(command, args, options = {}) {",
    "  const invocation = buildRemoteInvocation(command, args);",
    "  return await new Promise((resolve, reject) => {",
    "    const child = spawn(invocation.command, [...invocation.args], { stdio: ['pipe', 'pipe', 'pipe'] });",
    '    let stdout = "";',
    '    let stderr = "";',
    "    let settled = false;",
    "    let timedOut = false;",
    "    let timeoutHandle;",
    "    let killHandle;",
    "    const cleanup = () => {",
    "      if (timeoutHandle) clearTimeout(timeoutHandle);",
    "      if (killHandle) clearTimeout(killHandle);",
    '      options.signal?.removeEventListener("abort", onAbort);',
    "    };",
    "    const settle = (callback) => {",
    "      if (settled) return;",
    "      settled = true;",
    "      cleanup();",
    "      callback();",
    "    };",
    "    const onAbort = () => {",
    '      child.kill("SIGTERM");',
    '      settle(() => reject(new Error("Operation aborted")));',
    "    };",
    "    if (options.signal?.aborted) {",
    '      settle(() => reject(new Error("Operation aborted")));',
    "      return;",
    "    }",
    '    options.signal?.addEventListener("abort", onAbort, { once: true });',
    "    if (options.timeoutMs && options.timeoutMs > 0) {",
    "      timeoutHandle = setTimeout(() => {",
    "        timedOut = true;",
    '        child.kill("SIGTERM");',
    "        killHandle = setTimeout(() => {",
    '          child.kill("SIGKILL");',
    "        }, 1_000);",
    "      }, options.timeoutMs);",
    "    }",
    '    child.stdout.setEncoding("utf8");',
    '    child.stderr.setEncoding("utf8");',
    '    child.stdout.on("data", (chunk) => { stdout += chunk; });',
    '    child.stderr.on("data", (chunk) => { stderr += chunk; });',
    '    child.once("error", (error) => settle(() => reject(error)));',
    '    child.once("close", (code) => {',
    "      if (timedOut) {",
    "        settle(() => reject(new Error(`Command timed out after ${Math.floor((options.timeoutMs ?? 0) / 1000)}s.`)));",
    "        return;",
    "      }",
    "      if (!options.allowNonZeroExit && code && code !== 0) {",
    "        const detail = normalizeOutput(`${stdout}${stderr}`.trim());",
    "        settle(() => reject(new Error(detail || `Remote command failed with exit code ${code}.`)));",
    "        return;",
    "      }",
    "      settle(() => resolve({ stdout: normalizeOutput(stdout), stderr: normalizeOutput(stderr), exitCode: code ?? 0 }));",
    "    });",
    "    if (options.stdin !== undefined) {",
    "      child.stdin.end(options.stdin);",
    "    } else {",
    "      child.stdin.end();",
    "    }",
    "  });",
    "}",
    "",
    "function detectLineEnding(text) {",
    '  return text.includes("\\r\\n") ? "\\r\\n" : "\\n";',
    "}",
    "",
    "function stripBom(text) {",
    '  return text.startsWith("\\uFEFF") ? { bom: "\\uFEFF", text: text.slice(1) } : { bom: "", text };',
    "}",
    "",
    "function normalizeToLf(text) {",
    '  return text.replace(/\\r\\n/g, "\\n").replace(/\\r/g, "\\n");',
    "}",
    "",
    "function restoreLineEndings(text, lineEnding) {",
    '  return lineEnding === "\\r\\n" ? text.replace(/\\n/g, "\\r\\n") : text;',
    "}",
    "",
    "function applyEditsToContent(rawContent, edits, path) {",
    "  if (edits.length === 0) throw new Error('Edit input is invalid. Provide at least one replacement.');",
    "  const { bom, text } = stripBom(rawContent);",
    "  const lineEnding = detectLineEnding(text);",
    "  const normalizedContent = normalizeToLf(text);",
    "  const matches = edits.map((edit, index) => {",
    "    const oldText = normalizeToLf(edit.oldText);",
    "    const newText = normalizeToLf(edit.newText);",
    "    if (oldText.length === 0) throw new Error(`Edit ${index + 1} in ${path} has an empty oldText.`);",
    "    const start = normalizedContent.indexOf(oldText);",
    "    if (start === -1) throw new Error(`Could not find edit ${index + 1} oldText in ${path}.`);",
    "    const duplicate = normalizedContent.indexOf(oldText, start + 1);",
    "    if (duplicate !== -1) throw new Error(`Edit ${index + 1} oldText is not unique in ${path}.`);",
    "    return { start, end: start + oldText.length, newText };",
    "  });",
    "  matches.sort((left, right) => left.start - right.start);",
    "  for (let index = 1; index < matches.length; index += 1) {",
    "    if ((matches[index - 1]?.end ?? 0) > (matches[index]?.start ?? 0)) {",
    "      throw new Error(`Edit replacements overlap in ${path}.`);",
    "    }",
    "  }",
    '  let nextContent = "";',
    "  let cursor = 0;",
    "  for (const match of matches) {",
    "    nextContent += normalizedContent.slice(cursor, match.start);",
    "    nextContent += match.newText;",
    "    cursor = match.end;",
    "  }",
    "  nextContent += normalizedContent.slice(cursor);",
    "  return bom + restoreLineEndings(nextContent, lineEnding);",
    "}",
    "",
    "async function readRemoteFileContents(path) {",
    '  const script = [\'set -eu\', \'target=$1\', \'if [ ! -e "$target" ]; then printf "Path not found: %s\\\\n" "$target" >&2; exit 1; fi\', \'if [ ! -f "$target" ]; then printf "Not a file: %s\\\\n" "$target" >&2; exit 1; fi\', \'cat "$target"\'].join(\'\\n\');',
    "  const result = await execRemote('sh', ['-lc', script, 'bigbud-mcp-read-full', path]);",
    "  return result.stdout;",
    "}",
    "",
    "async function callTool(name, args) {",
    "  switch (name) {",
    "    case 'read': {",
    "      const start = Math.max(1, Number(args?.offset ?? 1));",
    "      const effectiveLimit = Math.max(1, Math.min(Number(args?.limit ?? DEFAULT_READ_LIMIT), DEFAULT_READ_LIMIT));",
    "      const end = start + effectiveLimit - 1;",
    "      const marker = '__BIGBUD_TOTAL_LINES__';",
    '      const script = [\'set -eu\', \'target=$1\', \'if [ ! -e "$target" ]; then printf "Path not found: %s\\\\n" "$target" >&2; exit 1; fi\', \'if [ ! -f "$target" ]; then printf "Not a file: %s\\\\n" "$target" >&2; exit 1; fi\', \'total_lines=$(awk "END { print NR }" "$target")\', \'printf "__BIGBUD_TOTAL_LINES__%s\\\\n" "$total_lines" >&2\', `sed -n "${start},${end}p" "$target"`].join(\'\\n\');',
    "      const result = await execRemote('sh', ['-lc', script, 'bigbud-mcp-read', String(args?.path ?? '')]);",
    "      const totalLine = result.stderr.split('\\n').find((line) => line.startsWith(marker));",
    "      const totalLines = totalLine ? Number(totalLine.slice(marker.length)) : Number.NaN;",
    "      let output = result.stdout.replace(/\\n$/, '');",
    "      if (output.length === 0) output = '[empty file]';",
    "      if (!Number.isNaN(totalLines) && end < totalLines) output += `\\n\\n[Showing lines ${start}-${end} of ${totalLines}. Use offset=${end + 1} to continue.]`;",
    "      return { content: textContent(output) };",
    "    }",
    "    case 'write': {",
    "      const script = ['set -eu', 'target=$1', 'mkdir -p \"$(dirname \"$target\")\"', 'cat > \"$target\"'].join('\\n');",
    "      await execRemote('sh', ['-lc', script, 'bigbud-mcp-write', String(args?.path ?? '')], { stdin: String(args?.content ?? '') });",
    "      return { content: textContent(`Wrote ${String(args?.path ?? '')}`) };",
    "    }",
    "    case 'edit': {",
    "      const edits = Array.isArray(args?.edits)",
    "        ? args.edits",
    "        : args?.oldText !== undefined && args?.newText !== undefined",
    "          ? [{ oldText: String(args.oldText), newText: String(args.newText) }]",
    "          : [];",
    "      if (edits.length === 0) throw new Error('Provide either edits[] or both oldText and newText.');",
    "      const path = String(args?.path ?? '');",
    "      const current = await readRemoteFileContents(path);",
    "      const next = applyEditsToContent(current, edits, path);",
    "      const script = ['set -eu', 'target=$1', 'mkdir -p \"$(dirname \"$target\")\"', 'cat > \"$target\"'].join('\\n');",
    "      await execRemote('sh', ['-lc', script, 'bigbud-mcp-edit', path], { stdin: next });",
    "      return { content: textContent(`Wrote ${path}`) };",
    "    }",
    "    case 'bash': {",
    "      const result = await execRemote('sh', ['-lc', String(args?.command ?? '')], { allowNonZeroExit: true });",
    "      const output = truncateOutput(`${result.stdout}${result.stderr}`.trim(), MAX_BASH_OUTPUT_CHARS);",
    "      return { content: textContent(output.length > 0 ? output : `[command exited with code ${result.exitCode}]`) };",
    "    }",
    "    case 'grep': {",
    "      const root = args?.path ? String(args.path) : (CONFIG.cwd ?? '.');",
    "      const pattern = String(args?.pattern ?? '');",
    "      const command = `if command -v rg >/dev/null 2>&1; then rg -n --no-heading --color never --max-count ${DEFAULT_GREP_LIMIT} -- ${shellEscapePosix(pattern)} ${shellEscapePosix(root)}; else grep -R -n -- ${shellEscapePosix(pattern)} ${shellEscapePosix(root)} | head -n ${DEFAULT_GREP_LIMIT}; fi`;",
    "      const result = await execRemote('sh', ['-lc', command], { allowNonZeroExit: true });",
    "      const output = `${result.stdout}${result.stderr}`.trim();",
    "      return { content: textContent(output.length > 0 ? output : '[no matches]') };",
    "    }",
    "    case 'glob': {",
    "      const root = args?.path ? String(args.path) : (CONFIG.cwd ?? '.');",
    "      const pattern = String(args?.pattern ?? '');",
    '      const command = `if ! command -v rg >/dev/null 2>&1; then printf "ripgrep is required for glob on the remote host.\\\\n" >&2; exit 1; fi; cd ${shellEscapePosix(root)} && rg --files -g ${shellEscapePosix(pattern)} | head -n ${DEFAULT_GLOB_LIMIT}`;',
    "      const result = await execRemote('sh', ['-lc', command]);",
    "      const output = result.stdout.trim();",
    "      return { content: textContent(output.length > 0 ? output : '[no matches]') };",
    "    }",
    "    case 'list': {",
    "      const root = args?.path ? String(args.path) : (CONFIG.cwd ?? '.');",
    "      const command = `find ${shellEscapePosix(root)} -mindepth 1 -maxdepth 1 | sort | head -n ${DEFAULT_LIST_LIMIT}`;",
    "      const result = await execRemote('sh', ['-lc', command], { allowNonZeroExit: true });",
    "      const output = result.stdout.trim();",
    "      return { content: textContent(output.length > 0 ? output : '[empty directory]') };",
    "    }",
    "    case 'apply_patch': {",
    "      const command = ['set -eu', 'if command -v git >/dev/null 2>&1; then git apply --whitespace=nowarn - || patch -p0 -N; else patch -p0 -N; fi'].join('\\n');",
    "      await execRemote('sh', ['-lc', command], { stdin: String(args?.patch ?? '') });",
    '      return { content: textContent("Applied patch") };',
    "    }",
    "    default:",
    "      throw new Error(`Unknown tool: ${name}`);",
    "  }",
    "}",
    "",
    "async function handleRequest(request) {",
    "  if (request.method === 'initialize') {",
    "    const requestedVersion = request.params?.protocolVersion;",
    "    negotiatedProtocolVersion = SUPPORTED_PROTOCOL_VERSIONS.includes(requestedVersion)",
    "      ? requestedVersion",
    "      : DEFAULT_NEGOTIATED_PROTOCOL_VERSION;",
    "    writeResponse(request.id, {",
    "      protocolVersion: negotiatedProtocolVersion,",
    "      capabilities: { tools: {} },",
    '      serverInfo: { name: "bigbud-remote-workspace", version: "0.1.0" },',
    "      instructions: `Bigbud remote workspace bridge. The actual workspace lives on ${CONFIG.destination}${CONFIG.cwd ? ` at ${CONFIG.cwd}` : ''}.`,",
    "    });",
    "    return;",
    "  }",
    "  if (request.method === 'notifications/initialized') return;",
    "  if (request.method === 'ping') { writeResponse(request.id, {}); return; }",
    "  if (request.method === 'tools/list') { writeResponse(request.id, { tools: TOOLS }); return; }",
    "  if (request.method === 'tools/call') {",
    "    try {",
    "      const result = await callTool(String(request.params?.name ?? ''), request.params?.arguments ?? {});",
    "      writeResponse(request.id, result);",
    "    } catch (error) {",
    "      writeResponse(request.id, { content: textContent(error instanceof Error ? error.message : String(error)), isError: true });",
    "    }",
    "    return;",
    "  }",
    "  writeError(request.id ?? null, -32601, `Method not found: ${String(request.method)}`);",
    "}",
    "",
    "function tryReadMessages() {",
    "  while (true) {",
    "    const headerEnd = stdinBuffer.indexOf('\\r\\n\\r\\n');",
    "    if (headerEnd === -1) return;",
    "    const headerText = stdinBuffer.slice(0, headerEnd).toString('utf8');",
    "    const match = headerText.match(/Content-Length:\\s*(\\d+)/i);",
    "    if (!match) { process.exitCode = 1; return; }",
    "    const contentLength = Number(match[1]);",
    "    const messageStart = headerEnd + 4;",
    "    if (stdinBuffer.length < messageStart + contentLength) return;",
    "    const rawMessage = stdinBuffer.slice(messageStart, messageStart + contentLength).toString('utf8');",
    "    stdinBuffer = stdinBuffer.slice(messageStart + contentLength);",
    "    let message;",
    "    try { message = JSON.parse(rawMessage); } catch { continue; }",
    "    if (message && typeof message === 'object' && 'method' in message) {",
    "      void handleRequest(message).catch((error) => {",
    "        writeError(message.id ?? null, -32000, error instanceof Error ? error.message : String(error));",
    "      });",
    "    }",
    "  }",
    "}",
    "",
    "process.stdin.on('data', (chunk) => {",
    "  stdinBuffer = Buffer.concat([stdinBuffer, Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk)]);",
    "  tryReadMessages();",
    "});",
    "process.stdin.resume();",
  ].join("\n");
}
