import type { ThreadOrchestrationHttpConfig } from "../../../orchestration-tools/threadOrchestrationBridge.shared.ts";
import { renderCallOrchestrationToolSource } from "../../../orchestration-tools/threadOrchestrationBridge.shared.ts";

export function renderPiRemoteWorkspaceBridgeSource(
  input: ThreadOrchestrationHttpConfig,
  workspaceRoot?: string,
): string {
  const config = JSON.stringify(input, null, 2);

  return [
    'import { Type } from "typebox";',
    'import { defineTool } from "@earendil-works/pi-coding-agent";',
    "",
    `const CONFIG = ${config} as const;`,
    `const WORKSPACE_ROOT = ${JSON.stringify(workspaceRoot ?? "the configured remote root")};`,
    "const DEFAULT_READ_LIMIT = 250;",
    "const MAX_BASH_OUTPUT_CHARS = 64 * 1024;",
    "function normalizeOutput(text: string): string {",
    '  return text.replace(/\\r\\n/g, "\\n").replace(/\\r/g, "\\n");',
    "}",
    "",
    renderCallOrchestrationToolSource(),
    "",
    "function textResult(text: string, details?: unknown) {",
    "  return {",
    '    content: [{ type: "text" as const, text }],',
    "    ...(details === undefined ? {} : { details }),",
    "  };",
    "}",
    "",
    "async function execRemote(",
    "  command: string,",
    "  args: ReadonlyArray<string>,",
    "  options?: {",
    "    readonly stdin?: string;",
    "    readonly timeoutMs?: number;",
    "    readonly signal?: AbortSignal;",
    "    readonly allowNonZeroExit?: boolean;",
    "  },",
    "): Promise<{ readonly stdout: string; readonly stderr: string; readonly exitCode: number }> {",
    "  const response = await callOrchestrationTool({",
    "    action: 'remote_workspace_process',",
    "    remoteCommand: command,",
    "    remoteArgs: args,",
    "    ...(options?.stdin !== undefined ? { remoteStdin: options.stdin } : {}),",
    "    remoteAllowNonZeroExit: options?.allowNonZeroExit === true,",
    "    remoteTimeoutMs: options?.timeoutMs ?? 30_000,",
    "    remoteMaxOutputBytes: 1024 * 1024,",
    "    remoteOutputMode: 'truncate',",
    "  }, options?.signal);",
    "  const result = response.result ?? {};",
    "  return {",
    "    stdout: normalizeOutput(String(result.stdout ?? '')),",
    "    stderr: normalizeOutput(String(result.stderr ?? '')),",
    "    exitCode: Number.isInteger(result.code) ? result.code : 0,",
    "  };",
    "}",
    "",
    'function detectLineEnding(text: string): "\\r\\n" | "\\n" {',
    '  return text.includes("\\r\\n") ? "\\r\\n" : "\\n";',
    "}",
    "",
    "function stripBom(text: string): { readonly bom: string; readonly text: string } {",
    '  return text.startsWith("\\uFEFF") ? { bom: "\\uFEFF", text: text.slice(1) } : { bom: "", text };',
    "}",
    "",
    "function normalizeToLf(text: string): string {",
    '  return text.replace(/\\r\\n/g, "\\n").replace(/\\r/g, "\\n");',
    "}",
    "",
    'function restoreLineEndings(text: string, lineEnding: "\\r\\n" | "\\n"): string {',
    '  return lineEnding === "\\r\\n" ? text.replace(/\\n/g, "\\r\\n") : text;',
    "}",
    "",
    "function applyEditsToContent(",
    "  rawContent: string,",
    "  edits: ReadonlyArray<{ readonly oldText: string; readonly newText: string }>,",
    "  path: string,",
    "): string {",
    "  if (edits.length === 0) {",
    '    throw new Error("Edit tool input is invalid. edits must contain at least one replacement.");',
    "  }",
    "",
    "  const { bom, text } = stripBom(rawContent);",
    "  const lineEnding = detectLineEnding(text);",
    "  const normalizedContent = normalizeToLf(text);",
    "  const matches = edits.map((edit, index) => {",
    "    const oldText = normalizeToLf(edit.oldText);",
    "    const newText = normalizeToLf(edit.newText);",
    "    if (oldText.length === 0) {",
    "      throw new Error(`Edit ${index + 1} in ${path} has an empty oldText.`);",
    "    }",
    "    const start = normalizedContent.indexOf(oldText);",
    "    if (start === -1) {",
    "      throw new Error(`Could not find edit ${index + 1} oldText in ${path}.`);",
    "    }",
    "    const duplicate = normalizedContent.indexOf(oldText, start + 1);",
    "    if (duplicate !== -1) {",
    "      throw new Error(`Edit ${index + 1} oldText is not unique in ${path}.`);",
    "    }",
    "    return { start, end: start + oldText.length, newText };",
    "  });",
    "",
    "  matches.sort((left, right) => left.start - right.start);",
    "  for (let index = 1; index < matches.length; index += 1) {",
    "    if ((matches[index - 1]?.end ?? 0) > (matches[index]?.start ?? 0)) {",
    "      throw new Error(`Edit replacements overlap in ${path}. Merge nearby edits into one block.`);",
    "    }",
    "  }",
    "",
    '  let nextContent = "";',
    "  let cursor = 0;",
    "  for (const match of matches) {",
    "    nextContent += normalizedContent.slice(cursor, match.start);",
    "    nextContent += match.newText;",
    "    cursor = match.end;",
    "  }",
    "  nextContent += normalizedContent.slice(cursor);",
    "  return bom + restoreLineEndings(nextContent, lineEnding);",
    "}",
    "",
    "const readTool = defineTool({",
    '  name: "read",',
    '  label: "read",',
    '  description: "Read a file from the remote workspace. Supports relative and absolute paths. Returns up to 250 lines by default; use offset/limit to continue.",',
    '  promptSnippet: "Read remote file contents",',
    "  parameters: Type.Object({",
    '    path: Type.String({ description: "Path to the remote file to read (relative or absolute)" }),',
    '    offset: Type.Optional(Type.Number({ description: "Line number to start reading from (1-indexed)" })),',
    '    limit: Type.Optional(Type.Number({ description: "Maximum number of lines to read" })),',
    "  }),",
    "  async execute(_toolCallId, { path, offset, limit }, signal) {",
    "    const start = Math.max(1, offset ?? 1);",
    "    const effectiveLimit = Math.max(1, Math.min(limit ?? DEFAULT_READ_LIMIT, DEFAULT_READ_LIMIT));",
    "    const end = start + effectiveLimit - 1;",
    "    const metadataMarker = '__BIGBUD_TOTAL_LINES__';",
    "    const script = [",
    '      "set -eu",',
    '      "target=$1",',
    '      \'if [ ! -e "$target" ]; then printf "Path not found: %s\\\\n" "$target" >&2; exit 1; fi\',',
    '      \'if [ ! -f "$target" ]; then printf "Not a file: %s\\\\n" "$target" >&2; exit 1; fi\',',
    '      \'if [ ! -r "$target" ]; then printf "Cannot read file: %s\\\\n" "$target" >&2; exit 1; fi\',',
    `      'total_lines=$(awk "END { print NR }" "$target")',`,
    `      'printf "__BIGBUD_TOTAL_LINES__%s\\\\n" "$total_lines" >&2',`,
    '      `sed -n "${start},${end}p" "$target"`,',
    '    ].join("\\n");',
    "    const result = await execRemote('sh', ['-lc', script, 'bigbud-pi-read', path], { signal });",
    "    const stderrLines = result.stderr.split('\\n').filter((line) => line.length > 0);",
    "    const totalLinesLine = stderrLines.find((line) => line.startsWith(metadataMarker));",
    "    const totalLines = totalLinesLine ? Number(totalLinesLine.slice(metadataMarker.length)) : Number.NaN;",
    "    if (!Number.isNaN(totalLines) && start > totalLines && totalLines > 0) {",
    "      throw new Error(`Offset ${start} is beyond end of file (${totalLines} lines total).`);",
    "    }",
    "    const outputLines = result.stdout.replace(/\\n$/, '');",
    '    let output = outputLines.length > 0 ? outputLines : "[empty file]";',
    "    if (!Number.isNaN(totalLines) && end < totalLines) {",
    "      output += `\\n\\n[Showing lines ${start}-${end} of ${totalLines}. Use offset=${end + 1} to continue.]`;",
    "    }",
    "    return textResult(output);",
    "  },",
    "});",
    "",
    "const writeTool = defineTool({",
    '  name: "write",',
    '  label: "write",',
    '  description: "Write a file in the remote workspace. Creates parent directories and overwrites the file if it exists.",',
    '  promptSnippet: "Create or overwrite remote files",',
    "  parameters: Type.Object({",
    '    path: Type.String({ description: "Path to the remote file to write (relative or absolute)" }),',
    '    content: Type.String({ description: "Content to write to the remote file" }),',
    "  }),",
    "  async execute(_toolCallId, { path, content }, signal) {",
    "    const script = [",
    '      "set -eu",',
    '      "target=$1",',
    '      \'mkdir -p "$(dirname "$target")"\',',
    "      'cat > \"$target\"',",
    '    ].join("\\n");',
    "    await execRemote('sh', ['-lc', script, 'bigbud-pi-write', path], {",
    "      signal,",
    "      stdin: content,",
    "    });",
    "    return textResult(`Successfully wrote ${content.length} bytes to ${path}.`);",
    "  },",
    "});",
    "",
    "const editTool = defineTool({",
    '  name: "edit",',
    '  label: "edit",',
    '  description: "Edit a remote file using exact text replacement. Use this for targeted changes to existing files.",',
    '  promptSnippet: "Make precise remote file edits",',
    "  parameters: Type.Object({",
    '    path: Type.String({ description: "Path to the remote file to edit (relative or absolute)" }),',
    "    edits: Type.Array(",
    "      Type.Object({",
    '        oldText: Type.String({ description: "Exact existing text to replace" }),',
    '        newText: Type.String({ description: "Replacement text" }),',
    "      }),",
    '      { description: "One or more exact replacements matched against the original file." },',
    "    ),",
    "  }),",
    "  async execute(_toolCallId, { path, edits }, signal) {",
    "    const readScript = [",
    '      "set -eu",',
    '      "target=$1",',
    '      \'if [ ! -e "$target" ]; then printf "Path not found: %s\\\\n" "$target" >&2; exit 1; fi\',',
    '      \'if [ ! -f "$target" ]; then printf "Not a file: %s\\\\n" "$target" >&2; exit 1; fi\',',
    '      \'if [ ! -r "$target" ]; then printf "Cannot read file: %s\\\\n" "$target" >&2; exit 1; fi\',',
    "      'cat \"$target\"',",
    '    ].join("\\n");',
    "    const existing = await execRemote('sh', ['-lc', readScript, 'bigbud-pi-edit-read', path], { signal });",
    "    const nextContent = applyEditsToContent(existing.stdout, edits, path);",
    "    const writeScript = [",
    '      "set -eu",',
    '      "target=$1",',
    "      'cat > \"$target\"',",
    '    ].join("\\n");',
    "    await execRemote('sh', ['-lc', writeScript, 'bigbud-pi-edit-write', path], {",
    "      signal,",
    "      stdin: nextContent,",
    "    });",
    "    return textResult(`Successfully replaced ${edits.length} block(s) in ${path}.`);",
    "  },",
    "});",
    "",
    "const bashTool = defineTool({",
    '  name: "bash",',
    '  label: "bash",',
    '  description: "Execute a bash command on the remote workspace host. Use this for search, git, tests, and general shell operations.",',
    '  promptSnippet: "Execute remote bash commands",',
    "  parameters: Type.Object({",
    '    command: Type.String({ description: "Remote bash command to execute" }),',
    '    timeout: Type.Optional(Type.Number({ description: "Timeout in seconds (optional)" })),',
    "  }),",
    "  async execute(_toolCallId, { command, timeout }, signal) {",
    "    const result = await execRemote('sh', ['-lc', command], {",
    "      signal,",
    "      ...(timeout && timeout > 0 ? { timeoutMs: timeout * 1000 } : {}),",
    "    });",
    "    const combined = `${result.stdout}${result.stderr}`;",
    "    const normalized = combined.length > 0 ? combined : '(no output)';",
    "    const truncated =",
    "      normalized.length > MAX_BASH_OUTPUT_CHARS",
    "        ? `${normalized.slice(-MAX_BASH_OUTPUT_CHARS)}\\n\\n[Output truncated to the last ${MAX_BASH_OUTPUT_CHARS} characters.]`",
    "        : normalized;",
    "    return textResult(truncated);",
    "  },",
    "});",
    "",
    "export default function bigbudRemoteWorkspaceBridge(pi: {",
    "  registerTool: (tool: unknown) => void;",
    "  on: (event: string, handler: (ctx: unknown, event: { systemPrompt?: string }) => unknown) => void;",
    "}) {",
    "  pi.registerTool(readTool);",
    "  pi.registerTool(writeTool);",
    "  pi.registerTool(editTool);",
    "  pi.registerTool(bashTool);",
    '  pi.on("before_agent_start", (_ctx, event) => ({',
    "    systemPrompt:",
    '      `${event.systemPrompt ?? ""}\\n\\nbigbud remote workspace mode: the actual workspace root is ${WORKSPACE_ROOT}. Ignore the local synthetic working directory. Use the provided read/write/edit tools for file access and use bash for search, git, tests, ls, grep, and other shell operations. Relative paths are resolved from the remote workspace root.`,',
    "  }));",
    "}",
    "",
  ].join("\n");
}
