import { MCP_SERVER_TEMPLATE_PRELUDE } from "../remote-workspace-bridge/remoteWorkspaceMcpBridge.template.shared.ts";
import {
  ORCHESTRATION_MCP_TOOL_DEFINITIONS,
  renderOrchestrationMcpConfig,
} from "./orchestrationMcpBridge.template.shared.ts";
import {
  renderCallOrchestrationToolSource,
  renderResolveCurrentThreadIdSource,
  type ThreadOrchestrationHttpConfig,
} from "./threadOrchestrationBridge.shared.ts";

export function renderOrchestrationMcpServerSource(input: ThreadOrchestrationHttpConfig): string {
  const config = renderOrchestrationMcpConfig(input);
  return [
    ...MCP_SERVER_TEMPLATE_PRELUDE,
    `const CONFIG = ${config};`,
    ...ORCHESTRATION_MCP_TOOL_DEFINITIONS,
    "let negotiatedProtocolVersion = DEFAULT_NEGOTIATED_PROTOCOL_VERSION;",
    "let stdinBuffer = Buffer.alloc(0);",
    "",
    "function textContent(text) {",
    '  return [{ type: "text", text }];',
    "}",
    "",
    "function imageContent(screenshot) {",
    "  if (!screenshot || typeof screenshot.dataBase64 !== 'string' || typeof screenshot.mimeType !== 'string') {",
    "    return [];",
    "  }",
    "  return [{ type: 'image', data: screenshot.dataBase64, mimeType: screenshot.mimeType }];",
    "}",
    "",
    "function writeMessage(message) {",
    "  const encoded = Buffer.from(JSON.stringify(message), 'utf8');",
    "  process.stdout.write(`Content-Length: ${encoded.length}\\r\\n\\r\\n`);",
    "  process.stdout.write(encoded);",
    "}",
    "",
    "function writeResponse(id, result) {",
    "  writeMessage({ jsonrpc: JSONRPC_VERSION, id, result });",
    "}",
    "",
    "function writeError(id, code, message) {",
    "  writeMessage({ jsonrpc: JSONRPC_VERSION, id, error: { code, message } });",
    "}",
    "",
    renderCallOrchestrationToolSource(),
    "",
    renderResolveCurrentThreadIdSource(),
    "",
    "async function callTool(name, args) {",
    "  const threadId = resolveCurrentThreadId();",
    "  switch (name) {",
    "    case 'rename_thread': {",
    "      const title = String(args?.title ?? '').trim();",
    "      if (title.length === 0) throw new Error('Thread title cannot be empty.');",
    "      const result = await callOrchestrationTool({ action: 'rename', threadId, title });",
    '      return { content: textContent(`Renamed thread to "${result.title ?? title}".`) };',
    "    }",
    "    case 'archive_thread': {",
    "      await callOrchestrationTool({ action: 'archive', threadId });",
    "      return { content: textContent('Archived the current thread.') };",
    "    }",
    "    case 'get_thread_status': {",
    "      const targetThreadId = String(args?.threadId ?? '').trim();",
    "      if (targetThreadId.length === 0) throw new Error('Thread ID is required.');",
    "      const result = await callOrchestrationTool({",
    "        action: 'get_status',",
    "        threadId: targetThreadId,",
    "      });",
    "      return { content: textContent(JSON.stringify(result.status ?? {}, null, 2)) };",
    "    }",
    "    case 'computer_use': {",
    "      const result = await callOrchestrationTool({",
    "        action: 'computer_use',",
    "        computerUseAction: args,",
    "      });",
    "      const content = [",
    "        ...textContent(JSON.stringify(result.result ?? {}, null, 2)),",
    "        ...imageContent(result.result?.screenshot),",
    "      ];",
    "      return { content };",
    "    }",
    "    default:",
    "      throw new Error(`Unknown tool: ${name}`);",
    "  }",
    "}",
    "",
    "function handleMessage(message) {",
    "  if (message.method === 'initialize') {",
    "    const requestedVersion = message.params?.protocolVersion;",
    "    negotiatedProtocolVersion = SUPPORTED_PROTOCOL_VERSIONS.includes(requestedVersion)",
    "      ? requestedVersion",
    "      : DEFAULT_NEGOTIATED_PROTOCOL_VERSION;",
    "    writeResponse(message.id, {",
    "      protocolVersion: negotiatedProtocolVersion,",
    "      capabilities: { tools: {} },",
    "      serverInfo: { name: 'bigbud-orchestration', version: '1.0.0' },",
    "    });",
    "    return;",
    "  }",
    "  if (message.method === 'notifications/initialized') {",
    "    return;",
    "  }",
    "  if (message.method === 'tools/list') {",
    "    writeResponse(message.id, { tools: TOOLS });",
    "    return;",
    "  }",
    "  if (message.method === 'tools/call') {",
    "    const name = message.params?.name;",
    "    const args = message.params?.arguments ?? {};",
    "    void callTool(String(name ?? ''), args)",
    "      .then((result) => writeResponse(message.id, result))",
    "      .catch((error) =>",
    "        writeError(message.id, -32000, error instanceof Error ? error.message : String(error)),",
    "      );",
    "    return;",
    "  }",
    "  if (message.id !== undefined) {",
    "    writeError(message.id, -32601, `Method not found: ${String(message.method ?? '')}`);",
    "  }",
    "}",
    "",
    "process.stdin.on('readable', () => {",
    "  let chunk;",
    "  while ((chunk = process.stdin.read()) !== null) {",
    "    stdinBuffer = Buffer.concat([stdinBuffer, chunk]);",
    "    while (true) {",
    "      const headerEnd = stdinBuffer.indexOf('\\r\\n\\r\\n');",
    "      if (headerEnd === -1) break;",
    "      const header = stdinBuffer.slice(0, headerEnd).toString('utf8');",
    "      const match = header.match(/Content-Length:\\s*(\\d+)/i);",
    "      if (!match) {",
    "        stdinBuffer = stdinBuffer.slice(headerEnd + 4);",
    "        continue;",
    "      }",
    "      const contentLength = Number(match[1]);",
    "      const totalLength = headerEnd + 4 + contentLength;",
    "      if (stdinBuffer.length < totalLength) break;",
    "      const body = stdinBuffer.slice(headerEnd + 4, totalLength).toString('utf8');",
    "      stdinBuffer = stdinBuffer.slice(totalLength);",
    "      try {",
    "        handleMessage(JSON.parse(body));",
    "      } catch (error) {",
    "        process.stderr.write(`Failed to parse MCP message: ${String(error)}\\n`);",
    "      }",
    "    }",
    "  }",
    "});",
    "",
  ].join("\n");
}
