import {
  COMPUTER_USE_ACCESSIBILITY_MAX_DEPTH,
  COMPUTER_USE_APP_NAME_MAX_CHARS,
  COMPUTER_USE_COORDINATE_MAX,
  COMPUTER_USE_COORDINATE_MIN,
  COMPUTER_USE_KEY_MAX_CHARS,
  COMPUTER_USE_SCROLL_DELTA_MAX,
  COMPUTER_USE_SCROLL_DELTA_MIN,
  COMPUTER_USE_TEXT_MAX_CHARS,
  COMPUTER_USE_URL_MAX_CHARS,
  COMPUTER_USE_WAIT_DURATION_MS_MAX,
} from "@bigbud/contracts/orchestration/computerUse.ts";
import {
  ARCHIVE_THREAD_TOOL_DESCRIPTION,
  COMPUTER_USE_TOOL_DESCRIPTION,
  GET_THREAD_STATUS_TOOL_DESCRIPTION,
  RENAME_THREAD_TOOL_DESCRIPTION,
  renderThreadOrchestrationConfigLiteral,
  type ThreadOrchestrationHttpConfig,
} from "./threadOrchestrationBridge.shared.ts";

export const ORCHESTRATION_MCP_SERVER_NAME = "bigbud_orchestration";

export const ORCHESTRATION_MCP_TOOL_DEFINITIONS = [
  "const TOOLS = [",
  "  {",
  '    name: "rename_thread",',
  `    description: ${JSON.stringify(RENAME_THREAD_TOOL_DESCRIPTION)},`,
  "    inputSchema: {",
  '      type: "object",',
  "      properties: {",
  '        title: { type: "string", description: "New thread title" },',
  "      },",
  '      required: ["title"],',
  "      additionalProperties: false,",
  "    },",
  "  },",
  "  {",
  '    name: "computer_use",',
  `    description: ${JSON.stringify(COMPUTER_USE_TOOL_DESCRIPTION)},`,
  "    inputSchema: {",
  '      type: "object",',
  "      properties: {",
  "        action: {",
  '          type: "string",',
  '          enum: ["capture", "navigate", "click", "drag", "scroll", "type", "key", "wait", "get_page_info", "list_windows", "list_apps", "check_permissions", "doctor", "launch_app", "focus_app", "get_accessibility_tree"],',
  "        },",
  '        surface: { type: "string", enum: ["browser", "desktop"] },',
  `        url: { type: "string", maxLength: ${COMPUTER_USE_URL_MAX_CHARS}, pattern: "^https?://" },`,
  `        x: { type: "number", minimum: ${COMPUTER_USE_COORDINATE_MIN}, maximum: ${COMPUTER_USE_COORDINATE_MAX} },`,
  `        y: { type: "number", minimum: ${COMPUTER_USE_COORDINATE_MIN}, maximum: ${COMPUTER_USE_COORDINATE_MAX} },`,
  '        button: { type: "string", enum: ["left", "middle", "right"] },',
  `        startX: { type: "number", minimum: ${COMPUTER_USE_COORDINATE_MIN}, maximum: ${COMPUTER_USE_COORDINATE_MAX} },`,
  `        startY: { type: "number", minimum: ${COMPUTER_USE_COORDINATE_MIN}, maximum: ${COMPUTER_USE_COORDINATE_MAX} },`,
  `        endX: { type: "number", minimum: ${COMPUTER_USE_COORDINATE_MIN}, maximum: ${COMPUTER_USE_COORDINATE_MAX} },`,
  `        endY: { type: "number", minimum: ${COMPUTER_USE_COORDINATE_MIN}, maximum: ${COMPUTER_USE_COORDINATE_MAX} },`,
  `        deltaX: { type: "number", minimum: ${COMPUTER_USE_SCROLL_DELTA_MIN}, maximum: ${COMPUTER_USE_SCROLL_DELTA_MAX} },`,
  `        deltaY: { type: "number", minimum: ${COMPUTER_USE_SCROLL_DELTA_MIN}, maximum: ${COMPUTER_USE_SCROLL_DELTA_MAX} },`,
  `        text: { type: "string", maxLength: ${COMPUTER_USE_TEXT_MAX_CHARS} },`,
  `        key: { type: "string", maxLength: ${COMPUTER_USE_KEY_MAX_CHARS} },`,
  `        durationMs: { type: "integer", minimum: 1, maximum: ${COMPUTER_USE_WAIT_DURATION_MS_MAX} },`,
  '        prompt: { type: "boolean" },',
  `        name: { type: "string", maxLength: ${COMPUTER_USE_APP_NAME_MAX_CHARS} },`,
  '        pid: { type: "integer", minimum: 1 },',
  '        windowId: { type: "integer", minimum: 1 },',
  `        maxDepth: { type: "integer", minimum: 1, maximum: ${COMPUTER_USE_ACCESSIBILITY_MAX_DEPTH} },`,
  '        captureAfter: { type: "boolean" },',
  "      },",
  '      required: ["action"],',
  "      additionalProperties: false,",
  "    },",
  "  },",
  "  {",
  '    name: "archive_thread",',
  `    description: ${JSON.stringify(ARCHIVE_THREAD_TOOL_DESCRIPTION)},`,
  "    inputSchema: {",
  '      type: "object",',
  "      properties: {},",
  "      required: [],",
  "      additionalProperties: false,",
  "    },",
  "  },",
  "  {",
  '    name: "get_thread_status",',
  `    description: ${JSON.stringify(GET_THREAD_STATUS_TOOL_DESCRIPTION)},`,
  "    inputSchema: {",
  '      type: "object",',
  "      properties: {",
  '        threadId: { type: "string", description: "Thread ID to inspect" },',
  "      },",
  '      required: ["threadId"],',
  "      additionalProperties: false,",
  "    },",
  "  },",
  "];",
  "",
];

export function renderOrchestrationMcpConfig(input: ThreadOrchestrationHttpConfig): string {
  return renderThreadOrchestrationConfigLiteral(input);
}
