import {
  COMPUTER_USE_TOOL_DESCRIPTION,
  renderCallOrchestrationToolSource,
} from "./threadOrchestrationBridge.shared.ts";

export const COMPUTER_USE_ACTION_ENUM = [
  "capture",
  "navigate",
  "click",
  "drag",
  "scroll",
  "type",
  "key",
  "wait",
  "get_page_info",
  "list_windows",
  "list_apps",
  "check_permissions",
  "doctor",
  "launch_app",
  "focus_app",
  "get_accessibility_tree",
] as const;

export const COPILOT_COMPUTER_USE_PARAMETERS = {
  type: "object",
  properties: {
    action: { type: "string", enum: [...COMPUTER_USE_ACTION_ENUM] },
    surface: { type: "string", enum: ["browser", "desktop"] },
    url: { type: "string" },
    x: { type: "number" },
    y: { type: "number" },
    button: { type: "string", enum: ["left", "middle", "right"] },
    startX: { type: "number" },
    startY: { type: "number" },
    endX: { type: "number" },
    endY: { type: "number" },
    deltaX: { type: "number" },
    deltaY: { type: "number" },
    text: { type: "string" },
    key: { type: "string" },
    durationMs: { type: "integer", minimum: 1 },
    prompt: { type: "boolean" },
    name: { type: "string" },
    pid: { type: "integer", minimum: 1 },
    windowId: { type: "integer", minimum: 1 },
    maxDepth: { type: "integer", minimum: 1 },
    captureAfter: { type: "boolean" },
  },
  required: ["action"],
  additionalProperties: false,
} as const;

export function renderPiComputerUseToolSource(): string {
  return [
    "const computerUseTool = defineTool({",
    '  name: "computer_use",',
    '  label: "computer_use",',
    `  description: ${JSON.stringify(COMPUTER_USE_TOOL_DESCRIPTION)},`,
    "  parameters: Type.Object({",
    '    action: Type.String({ description: "Computer-use action name" }),',
    '    surface: Type.Optional(Type.Union([Type.Literal("browser"), Type.Literal("desktop")])),',
    "    url: Type.Optional(Type.String()),",
    "    x: Type.Optional(Type.Number()),",
    "    y: Type.Optional(Type.Number()),",
    '    button: Type.Optional(Type.Union([Type.Literal("left"), Type.Literal("middle"), Type.Literal("right")])),',
    "    startX: Type.Optional(Type.Number()),",
    "    startY: Type.Optional(Type.Number()),",
    "    endX: Type.Optional(Type.Number()),",
    "    endY: Type.Optional(Type.Number()),",
    "    deltaX: Type.Optional(Type.Number()),",
    "    deltaY: Type.Optional(Type.Number()),",
    "    text: Type.Optional(Type.String()),",
    "    key: Type.Optional(Type.String()),",
    "    durationMs: Type.Optional(Type.Number()),",
    "    prompt: Type.Optional(Type.Boolean()),",
    "    name: Type.Optional(Type.String()),",
    "    pid: Type.Optional(Type.Number()),",
    "    windowId: Type.Optional(Type.Number()),",
    "    maxDepth: Type.Optional(Type.Number()),",
    "    captureAfter: Type.Optional(Type.Boolean()),",
    "  }),",
    "  async execute(_toolCallId, args) {",
    "    const result = await callOrchestrationTool({",
    "      action: 'computer_use',",
    "      computerUseAction: args,",
    "    });",
    "    return textResult(JSON.stringify(result.result ?? {}, null, 2));",
    "  },",
    "});",
  ].join("\n");
}

export { COMPUTER_USE_TOOL_DESCRIPTION, renderCallOrchestrationToolSource };
