import {
  ARCHIVE_THREAD_TOOL_DESCRIPTION,
  COMPUTER_USE_TOOL_DESCRIPTION,
  GET_THREAD_STATUS_TOOL_DESCRIPTION,
  RENAME_THREAD_TOOL_DESCRIPTION,
  renderThreadOrchestrationConfigLiteral,
  type ThreadOrchestrationHttpConfig,
} from "./threadOrchestrationBridge.shared.ts";

export const ORCHESTRATION_MCP_SERVER_NAME = "bigbud_orchestration";

export const ORCHESTRATION_MCP_TOOL_DEFINITIONS = [
  "const TOOLS = [",
  "  {",
  '    name: "rename_thread",',
  `    description: ${JSON.stringify(RENAME_THREAD_TOOL_DESCRIPTION)},`,
  "    inputSchema: {",
  '      type: "object",',
  "      properties: {",
  '        title: { type: "string", description: "New thread title" },',
  "      },",
  '      required: ["title"],',
  "      additionalProperties: false,",
  "    },",
  "  },",
  "  {",
  '    name: "computer_use",',
  `    description: ${JSON.stringify(COMPUTER_USE_TOOL_DESCRIPTION)},`,
  "    inputSchema: {",
  '      type: "object",',
  "      properties: {",
  "        action: {",
  '          type: "string",',
  '          enum: ["capture", "navigate", "click", "drag", "scroll", "type", "key", "wait", "get_page_info", "list_windows", "list_apps", "check_permissions", "doctor", "launch_app", "focus_app", "get_accessibility_tree"],',
  "        },",
  '        surface: { type: "string", enum: ["browser", "desktop"] },',
  '        url: { type: "string" },',
  '        x: { type: "number" },',
  '        y: { type: "number" },',
  '        button: { type: "string", enum: ["left", "middle", "right"] },',
  '        startX: { type: "number" },',
  '        startY: { type: "number" },',
  '        endX: { type: "number" },',
  '        endY: { type: "number" },',
  '        deltaX: { type: "number" },',
  '        deltaY: { type: "number" },',
  '        text: { type: "string" },',
  '        key: { type: "string" },',
  '        durationMs: { type: "integer", minimum: 1 },',
  '        prompt: { type: "boolean" },',
  '        name: { type: "string" },',
  '        pid: { type: "integer", minimum: 1 },',
  '        windowId: { type: "integer", minimum: 1 },',
  '        maxDepth: { type: "integer", minimum: 1 },',
  '        captureAfter: { type: "boolean" },',
  "      },",
  '      required: ["action"],',
  "      additionalProperties: false,",
  "    },",
  "  },",
  "  {",
  '    name: "archive_thread",',
  `    description: ${JSON.stringify(ARCHIVE_THREAD_TOOL_DESCRIPTION)},`,
  "    inputSchema: {",
  '      type: "object",',
  "      properties: {},",
  "      required: [],",
  "      additionalProperties: false,",
  "    },",
  "  },",
  "  {",
  '    name: "get_thread_status",',
  `    description: ${JSON.stringify(GET_THREAD_STATUS_TOOL_DESCRIPTION)},`,
  "    inputSchema: {",
  '      type: "object",',
  "      properties: {",
  '        threadId: { type: "string", description: "Thread ID to inspect" },',
  "      },",
  '      required: ["threadId"],',
  "      additionalProperties: false,",
  "    },",
  "  },",
  "];",
  "",
];

export function renderOrchestrationMcpConfig(input: ThreadOrchestrationHttpConfig): string {
  return renderThreadOrchestrationConfigLiteral(input);
}
