import { renderPiComputerUseToolSource } from "./orchestrationComputerUseTool.shared.ts";
import { renderPiBrowserToolSource } from "./orchestrationBrowserTool.shared.ts";
import {
  ARCHIVE_THREAD_TOOL_DESCRIPTION,
  CREATE_THREAD_TOOL_DESCRIPTION,
  GET_THREAD_STATUS_TOOL_DESCRIPTION,
  LIST_PINNED_THREADS_TOOL_DESCRIPTION,
  LIST_THREADS_TOOL_DESCRIPTION,
  PIN_THREAD_TOOL_DESCRIPTION,
  RENAME_THREAD_TOOL_DESCRIPTION,
  SEND_THREAD_MESSAGE_TOOL_DESCRIPTION,
  UNPIN_THREAD_TOOL_DESCRIPTION,
  renderCallOrchestrationToolSource,
  renderResolveCurrentThreadIdSource,
  renderThreadOrchestrationConfigLiteral,
  type ThreadOrchestrationHttpConfig,
} from "./threadOrchestrationBridge.shared.ts";
import {
  BIGBUD_PLAN_TRACKING_TOOL_DESCRIPTION,
  BIGBUD_PLAN_TRACKING_TOOL_NAME,
  BIGBUD_PLAN_TRACKING_TOOL_SUCCESS_MESSAGE,
} from "./threadPlanTrackingTool.shared.ts";
import {
  READ_CAPABILITY_GUIDE_TOOL_DESCRIPTION,
  SEARCH_CAPABILITIES_TOOL_DESCRIPTION,
} from "./capabilityCatalogTool.shared.ts";
import { LIST_THREADS_MAX_LIMIT } from "./ThreadOrchestrationTools.listThreads.ts";
import { AGENT_WORKSPACE_TOOL_SPECS } from "./AgentWorkspaceToolSpecs.ts";

export function renderPiOrchestrationBridgeSource(input: ThreadOrchestrationHttpConfig): string {
  const config = renderThreadOrchestrationConfigLiteral(input);
  return [
    'import { Type } from "@earendil-works/pi-ai";',
    'import { defineTool } from "@earendil-works/pi-coding-agent";',
    'import { randomUUID } from "node:crypto";',
    "",
    `const CONFIG = ${config};`,
    "const SOURCE_MESSAGE_ID = randomUUID();",
    "",
    "function textResult(message) {",
    "  return {",
    '    content: [{ type: "text", text: message }],',
    "  };",
    "}",
    "",
    renderCallOrchestrationToolSource(),
    "",
    renderResolveCurrentThreadIdSource(),
    "",
    `const workspaceToolSpecs = ${JSON.stringify(AGENT_WORKSPACE_TOOL_SPECS)};`,
    "const workspaceTools = workspaceToolSpecs.map((spec) => defineTool({",
    "  name: spec.name,",
    "  label: spec.name,",
    "  description: spec.description,",
    "  parameters: spec.inputSchema,",
    "  async execute(_toolCallId, args) {",
    "    const result = await callOrchestrationTool({ action: 'workspace', workspaceTool: spec.name, workspaceArguments: args ?? {} });",
    "    return textResult(JSON.stringify(result.result ?? {}, null, 2));",
    "  },",
    "}));",
    "",
    "const searchCapabilitiesTool = defineTool({",
    '  name: "search_capabilities",',
    '  label: "search_capabilities",',
    `  description: ${JSON.stringify(SEARCH_CAPABILITIES_TOOL_DESCRIPTION)},`,
    "  parameters: Type.Object({",
    '    query: Type.Optional(Type.String({ description: "Task or keywords to match" })),',
    "  }),",
    "  async execute(_toolCallId, { query }) {",
    "    const result = await callOrchestrationTool({",
    "      action: 'search_capabilities',",
    "      query: String(query ?? ''),",
    "    });",
    "    return textResult(JSON.stringify(result.result ?? {}, null, 2));",
    "  },",
    "});",
    "",
    "const readCapabilityGuideTool = defineTool({",
    '  name: "read_capability_guide",',
    '  label: "read_capability_guide",',
    `  description: ${JSON.stringify(READ_CAPABILITY_GUIDE_TOOL_DESCRIPTION)},`,
    "  parameters: Type.Object({",
    '    capabilityId: Type.String({ description: "Capability ID or logical Track URI" }),',
    '    section: Type.Optional(Type.Union([Type.Literal("summary"), Type.Literal("workflow"), Type.Literal("permissions"), Type.Literal("examples"), Type.Literal("full")])),',
    "  }),",
    "  async execute(_toolCallId, { capabilityId, section }) {",
    "    const trimmed = String(capabilityId ?? '').trim();",
    "    if (trimmed.length === 0) throw new Error('Capability ID is required.');",
    "    const result = await callOrchestrationTool({",
    "      action: 'read_capability_guide',",
    "      capabilityId: trimmed,",
    "      ...(section ? { section: String(section) } : {}),",
    "    });",
    "    return textResult(JSON.stringify(result.result ?? {}, null, 2));",
    "  },",
    "});",
    "",
    "const createThreadTool = defineTool({",
    '  name: "create_thread",',
    '  label: "create_thread",',
    `  description: ${JSON.stringify(CREATE_THREAD_TOOL_DESCRIPTION)},`,
    "  parameters: Type.Object({",
    '    title: Type.String({ description: "Title for the new standalone bigbud thread" }),',
    '    task: Type.String({ description: "Task for the new standalone bigbud thread" }),',
    '    projectId: Type.Optional(Type.String({ description: "Optional project ID" })),',
    '    workspacePath: Type.Optional(Type.String({ description: "Optional workspace path" })),',
    '    watchForCompletion: Type.Optional(Type.Boolean({ description: "Wait for the thread to complete" })),',
    "  }),",
    "  async execute(toolCallId, { title, task, projectId, workspacePath, watchForCompletion }) {",
    "    const trimmedTitle = String(title ?? '').trim();",
    "    const trimmedTask = String(task ?? '').trim();",
    "    if (trimmedTitle.length === 0) throw new Error('Thread title cannot be empty.');",
    "    if (trimmedTask.length === 0) throw new Error('Thread task cannot be empty.');",
    "    const result = await callOrchestrationTool({",
    "      action: 'create_thread',",
    "      title: trimmedTitle,",
    "      task: trimmedTask,",
    "      ...(projectId ? { projectId: String(projectId).trim() } : {}),",
    "      ...(workspacePath ? { workspacePath: String(workspacePath).trim() } : {}),",
    "      watchForCompletion: watchForCompletion === true,",
    "      invocationId: toolCallId,",
    "      sourceMessageId: SOURCE_MESSAGE_ID,",
    "    });",
    "    return textResult(JSON.stringify(result.result ?? {}, null, 2));",
    "  },",
    "});",
    "",
    "const renameThreadTool = defineTool({",
    '  name: "rename_thread",',
    '  label: "rename_thread",',
    `  description: ${JSON.stringify(RENAME_THREAD_TOOL_DESCRIPTION)},`,
    "  parameters: Type.Object({",
    '    title: Type.String({ description: "New thread title" }),',
    "  }),",
    "  async execute(_toolCallId, { title }) {",
    "    const trimmed = String(title ?? '').trim();",
    "    if (trimmed.length === 0) throw new Error('Thread title cannot be empty.');",
    "    const result = await callOrchestrationTool({",
    "      action: 'rename',",
    "      threadId: resolveCurrentThreadId(),",
    "      title: trimmed,",
    "    });",
    '    return textResult(`Renamed thread to "${result.title ?? trimmed}".`);',
    "  },",
    "});",
    "",
    "const archiveThreadTool = defineTool({",
    '  name: "archive_thread",',
    '  label: "archive_thread",',
    `  description: ${JSON.stringify(ARCHIVE_THREAD_TOOL_DESCRIPTION)},`,
    "  parameters: Type.Object({}),",
    "  async execute() {",
    "    await callOrchestrationTool({ action: 'archive', threadId: resolveCurrentThreadId() });",
    "    return textResult('Archived the current thread.');",
    "  },",
    "});",
    "",
    "const getThreadStatusTool = defineTool({",
    '  name: "get_thread_status",',
    '  label: "get_thread_status",',
    `  description: ${JSON.stringify(GET_THREAD_STATUS_TOOL_DESCRIPTION)},`,
    "  parameters: Type.Object({",
    '    threadId: Type.String({ description: "Thread ID to inspect" }),',
    "  }),",
    "  async execute(_toolCallId, { threadId }) {",
    "    const trimmed = String(threadId ?? '').trim();",
    "    if (trimmed.length === 0) throw new Error('Thread ID is required.');",
    "    const result = await callOrchestrationTool({",
    "      action: 'get_status',",
    "      threadId: trimmed,",
    "    });",
    "    return textResult(JSON.stringify(result.status ?? {}, null, 2));",
    "  },",
    "});",
    "",
    "const sendThreadMessageTool = defineTool({",
    '  name: "send_thread_message",',
    '  label: "send_thread_message",',
    `  description: ${JSON.stringify(SEND_THREAD_MESSAGE_TOOL_DESCRIPTION)},`,
    "  parameters: Type.Object({ threadId: Type.String(), message: Type.String(), delivery: Type.Optional(Type.Union([Type.Literal('auto'), Type.Literal('queue')])) }),",
    "  async execute(toolCallId, { threadId, message, delivery }) {",
    "    const result = await callOrchestrationTool({ action: 'send_thread_message', threadId: String(threadId).trim(), message: String(message).trim(), delivery: delivery === 'queue' ? 'queue' : 'auto', invocationId: toolCallId });",
    "    return textResult(JSON.stringify(result.result ?? {}, null, 2));",
    "  },",
    "});",
    "",
    "const listThreadsTool = defineTool({",
    '  name: "list_threads",',
    '  label: "list_threads",',
    `  description: ${JSON.stringify(LIST_THREADS_TOOL_DESCRIPTION)},`,
    "  parameters: Type.Object({",
    '    projectId: Type.Optional(Type.String({ description: "Project ID; defaults to the current project" })),',
    "    status: Type.Optional(Type.Union([Type.Literal('active'), Type.Literal('archived'), Type.Literal('all')])),",
    `    limit: Type.Optional(Type.Integer({ minimum: 1, maximum: ${LIST_THREADS_MAX_LIMIT} })),`,
    "    includeExcerpt: Type.Optional(Type.Boolean()),",
    "  }),",
    "  async execute(_toolCallId, { projectId, status, limit, includeExcerpt }) {",
    "    const trimmedProjectId = String(projectId ?? '').trim();",
    "    const result = await callOrchestrationTool({",
    "      action: 'list_threads',",
    "      ...(trimmedProjectId ? { projectId: trimmedProjectId } : {}),",
    "      ...(status ? { status } : {}),",
    "      ...(Number.isFinite(limit) ? { limit: Number(limit) } : {}),",
    "      includeExcerpt: includeExcerpt === true,",
    "    });",
    "    return textResult(JSON.stringify(result.result ?? {}, null, 2));",
    "  },",
    "});",
    "",
    "const listPinnedThreadsTool = defineTool({",
    '  name: "list_pinned_threads",',
    '  label: "list_pinned_threads",',
    `  description: ${JSON.stringify(LIST_PINNED_THREADS_TOOL_DESCRIPTION)},`,
    "  parameters: Type.Object({}),",
    "  async execute() {",
    "    const result = await callOrchestrationTool({ action: 'list_pinned' });",
    "    return textResult(JSON.stringify(result.result ?? {}, null, 2));",
    "  },",
    "});",
    "",
    "function createSetPinnedTool({ name, description, pinned }) {",
    "  return defineTool({",
    "    name,",
    "    label: name,",
    "    description,",
    "    parameters: Type.Object({",
    '      threadId: Type.String({ description: pinned ? "Thread ID to pin" : "Thread ID to unpin" }),',
    "    }),",
    "    async execute(_toolCallId, { threadId }) {",
    "      const trimmed = String(threadId ?? '').trim();",
    "      if (trimmed.length === 0) throw new Error('Thread ID is required.');",
    "      const result = await callOrchestrationTool({",
    "        action: pinned ? 'pin' : 'unpin',",
    "        threadId: trimmed,",
    "      });",
    "      return textResult(JSON.stringify(result.result ?? {}, null, 2));",
    "    },",
    "  });",
    "}",
    "",
    "const pinThreadTool = createSetPinnedTool({",
    "  name: 'pin_thread',",
    `  description: ${JSON.stringify(PIN_THREAD_TOOL_DESCRIPTION)},`,
    "  pinned: true,",
    "});",
    "",
    "const unpinThreadTool = createSetPinnedTool({",
    "  name: 'unpin_thread',",
    `  description: ${JSON.stringify(UNPIN_THREAD_TOOL_DESCRIPTION)},`,
    "  pinned: false,",
    "});",
    "",
    "const updatePlanTool = defineTool({",
    `  name: ${JSON.stringify(BIGBUD_PLAN_TRACKING_TOOL_NAME)},`,
    `  label: ${JSON.stringify(BIGBUD_PLAN_TRACKING_TOOL_NAME)},`,
    `  description: ${JSON.stringify(BIGBUD_PLAN_TRACKING_TOOL_DESCRIPTION)},`,
    "  parameters: Type.Object({",
    '    explanation: Type.Optional(Type.String({ description: "Optional short note about the current plan." })),',
    "    plan: Type.Array(",
    "      Type.Object({",
    '        step: Type.String({ description: "Plan step label" }),',
    '        status: Type.Union([Type.Literal("pending"), Type.Literal("inProgress"), Type.Literal("completed")]),',
    "      }),",
    '      { description: "The full current plan for this turn." },',
    "    ),",
    "  }),",
    "  async execute() {",
    `    return textResult(${JSON.stringify(BIGBUD_PLAN_TRACKING_TOOL_SUCCESS_MESSAGE)});`,
    "  },",
    "});",
    "",
    renderPiComputerUseToolSource(),
    "",
    renderPiBrowserToolSource(),
    "",
    "export default function bigbudOrchestrationBridge(pi) {",
    "  for (const tool of workspaceTools) pi.registerTool(tool);",
    "  pi.registerTool(searchCapabilitiesTool);",
    "  pi.registerTool(readCapabilityGuideTool);",
    "  pi.registerTool(createThreadTool);",
    "  pi.registerTool(renameThreadTool);",
    "  pi.registerTool(archiveThreadTool);",
    "  pi.registerTool(getThreadStatusTool);",
    "  pi.registerTool(sendThreadMessageTool);",
    "  pi.registerTool(listThreadsTool);",
    "  pi.registerTool(listPinnedThreadsTool);",
    "  pi.registerTool(pinThreadTool);",
    "  pi.registerTool(unpinThreadTool);",
    "  pi.registerTool(updatePlanTool);",
    "  pi.registerTool(computerUseTool);",
    "  pi.registerTool(browserTool);",
    "}",
    "",
  ].join("\n");
}
