import { renderPiComputerUseToolSource } from "./orchestrationComputerUseTool.shared.ts";
import {
  ARCHIVE_THREAD_TOOL_DESCRIPTION,
  GET_THREAD_STATUS_TOOL_DESCRIPTION,
  RENAME_THREAD_TOOL_DESCRIPTION,
  renderCallOrchestrationToolSource,
  renderResolveCurrentThreadIdSource,
  renderThreadOrchestrationConfigLiteral,
  type ThreadOrchestrationHttpConfig,
} from "./threadOrchestrationBridge.shared.ts";

export function renderPiOrchestrationBridgeSource(input: ThreadOrchestrationHttpConfig): string {
  const config = renderThreadOrchestrationConfigLiteral(input);
  return [
    'import { Type } from "@earendil-works/pi-ai";',
    'import { defineTool } from "@earendil-works/pi-coding-agent";',
    "",
    `const CONFIG = ${config};`,
    "",
    "function textResult(message) {",
    "  return {",
    '    content: [{ type: "text", text: message }],',
    "  };",
    "}",
    "",
    renderCallOrchestrationToolSource(),
    "",
    renderResolveCurrentThreadIdSource(),
    "",
    "const renameThreadTool = defineTool({",
    '  name: "rename_thread",',
    '  label: "rename_thread",',
    `  description: ${JSON.stringify(RENAME_THREAD_TOOL_DESCRIPTION)},`,
    "  parameters: Type.Object({",
    '    title: Type.String({ description: "New thread title" }),',
    "  }),",
    "  async execute(_toolCallId, { title }) {",
    "    const trimmed = String(title ?? '').trim();",
    "    if (trimmed.length === 0) throw new Error('Thread title cannot be empty.');",
    "    const result = await callOrchestrationTool({",
    "      action: 'rename',",
    "      threadId: resolveCurrentThreadId(),",
    "      title: trimmed,",
    "    });",
    '    return textResult(`Renamed thread to "${result.title ?? trimmed}".`);',
    "  },",
    "});",
    "",
    "const archiveThreadTool = defineTool({",
    '  name: "archive_thread",',
    '  label: "archive_thread",',
    `  description: ${JSON.stringify(ARCHIVE_THREAD_TOOL_DESCRIPTION)},`,
    "  parameters: Type.Object({}),",
    "  async execute() {",
    "    await callOrchestrationTool({ action: 'archive', threadId: resolveCurrentThreadId() });",
    "    return textResult('Archived the current thread.');",
    "  },",
    "});",
    "",
    "const getThreadStatusTool = defineTool({",
    '  name: "get_thread_status",',
    '  label: "get_thread_status",',
    `  description: ${JSON.stringify(GET_THREAD_STATUS_TOOL_DESCRIPTION)},`,
    "  parameters: Type.Object({",
    '    threadId: Type.String({ description: "Thread ID to inspect" }),',
    "  }),",
    "  async execute(_toolCallId, { threadId }) {",
    "    const trimmed = String(threadId ?? '').trim();",
    "    if (trimmed.length === 0) throw new Error('Thread ID is required.');",
    "    const result = await callOrchestrationTool({",
    "      action: 'get_status',",
    "      threadId: trimmed,",
    "    });",
    "    return textResult(JSON.stringify(result.status ?? {}, null, 2));",
    "  },",
    "});",
    "",
    renderPiComputerUseToolSource(),
    "",
    "export default function bigbudOrchestrationBridge(pi) {",
    "  pi.registerTool(renameThreadTool);",
    "  pi.registerTool(archiveThreadTool);",
    "  pi.registerTool(getThreadStatusTool);",
    "  pi.registerTool(computerUseTool);",
    "}",
    "",
  ].join("\n");
}
