import {
  ARCHIVE_THREAD_TOOL_DESCRIPTION,
  RENAME_THREAD_TOOL_DESCRIPTION,
  renderCallOrchestrationToolSource,
  renderResolveCurrentThreadIdSource,
  renderThreadOrchestrationConfigLiteral,
  type ThreadOrchestrationHttpConfig,
} from "./threadOrchestrationBridge.shared.ts";

export function renderPiOrchestrationBridgeSource(input: ThreadOrchestrationHttpConfig): string {
  const config = renderThreadOrchestrationConfigLiteral(input);
  return [
    'import { Type } from "@earendil-works/pi-ai";',
    'import { defineTool, type ExtensionAPI } from "@earendil-works/pi-coding-agent";',
    "",
    `const CONFIG = ${config} as const;`,
    "",
    "function textResult(message: string) {",
    "  return {",
    '    content: [{ type: "text" as const, text: message }],',
    "  };",
    "}",
    "",
    renderCallOrchestrationToolSource(true),
    "",
    renderResolveCurrentThreadIdSource(),
    "",
    "const renameThreadTool = defineTool({",
    '  name: "rename_thread",',
    '  label: "rename_thread",',
    `  description: ${JSON.stringify(RENAME_THREAD_TOOL_DESCRIPTION)},`,
    "  parameters: Type.Object({",
    '    title: Type.String({ description: "New thread title" }),',
    "  }),",
    "  async execute(_toolCallId, { title }) {",
    "    const trimmed = String(title ?? '').trim();",
    "    if (trimmed.length === 0) throw new Error('Thread title cannot be empty.');",
    "    const result = await callOrchestrationTool({",
    "      action: 'rename',",
    "      threadId: resolveCurrentThreadId(),",
    "      title: trimmed,",
    "    });",
    '    return textResult(`Renamed thread to "${result.title ?? trimmed}".`);',
    "  },",
    "});",
    "",
    "const archiveThreadTool = defineTool({",
    '  name: "archive_thread",',
    '  label: "archive_thread",',
    `  description: ${JSON.stringify(ARCHIVE_THREAD_TOOL_DESCRIPTION)},`,
    "  parameters: Type.Object({}),",
    "  async execute() {",
    "    await callOrchestrationTool({ action: 'archive', threadId: resolveCurrentThreadId() });",
    "    return textResult('Archived the current thread.');",
    "  },",
    "});",
    "",
    "export default function bigbudOrchestrationBridge(pi: ExtensionAPI) {",
    "  pi.registerTool(renameThreadTool);",
    "  pi.registerTool(archiveThreadTool);",
    "}",
    "",
  ].join("\n");
}
