/**
 * Renders the durable MCP identity ledger used by generated bridge processes.
 *
 * Each request owns one digest-named directory and sibling lock. The lock is
 * held from identity allocation through dispatch completion, so compaction and
 * overlapping bridge processes cannot reopen active work. New records are
 * fully initialized before an atomic rename publishes them.
 */
export type McpInvocationSurface = "orchestration" | "remote-workspace";

export function renderMcpInvocationIdentitySource(
  errorCode: string,
  surface: McpInvocationSurface,
): string {
  return [
    "const invocationStateFormatVersion = 3;",
    "const invocationCompletedRetentionCount = 128;",
    "const invocationCompletedRetentionMs = 7 * 24 * 60 * 60 * 1000;",
    `const invocationSurface = ${JSON.stringify(surface)};`,
    "const invocationProcessId = `${process.pid}:${Date.now()}:${process.hrtime.bigint()}`;",
    "let invocationStateQueue = Promise.resolve();",
    "function invocationStateKey(requestId) {",
    "  return `${typeof requestId}:${String(requestId)}`;",
    "}",
    "function normalizeInvocationFingerprint(value) {",
    "  if (value === null || typeof value !== 'object') return value;",
    "  if (Array.isArray(value)) return value.map(normalizeInvocationFingerprint);",
    "  return Object.fromEntries(Object.entries(value).sort(([left], [right]) => left.localeCompare(right)).map(([key, item]) => [key, normalizeInvocationFingerprint(item)]));",
    "}",
    "function invocationRequestDigest(request) {",
    "  const canonical = JSON.stringify(normalizeInvocationFingerprint({ method: request.method, params: request.params ?? null }));",
    "  return createHash('sha256').update(canonical).digest('hex');",
    "}",
    "function validInvocationMetadataId(request) {",
    "  const value = request.params?._meta?.['bigbud/toolInvocationId'];",
    "  return typeof value === 'string' && /^[\\x21-\\x7e]{1,200}$/.test(value) ? value : undefined;",
    "}",
    "function invocationRecordKey(request, identity) {",
    "  const metadataId = validInvocationMetadataId(request);",
    "  const source = metadataId ? `metadata\\0${identity}` : `request\\0${invocationStateKey(request.id)}\\0${invocationRequestDigest(request)}`;",
    "  return createHash('sha256').update(invocationSurface).update('\\0').update(source).digest('hex');",
    "}",
    "function invocationRecordPaths(recordKey) {",
    "  const recordDirectory = join(CONFIG.providerInvocationStatePath, recordKey);",
    "  return { recordDirectory, recordPath: join(recordDirectory, 'record.json'), lockDirectory: join(CONFIG.providerInvocationStatePath, `.${recordKey}.lock`) };",
    "}",
    "async function readInvocationRecord(recordKey) {",
    "  const { recordPath } = invocationRecordPaths(recordKey);",
    "  try {",
    "    const record = JSON.parse(await import('node:fs/promises').then(({ readFile }) => readFile(recordPath, 'utf8')));",
    "    if (record?.formatVersion !== invocationStateFormatVersion || record?.requestDigest !== recordKey || typeof record?.identity !== 'string' || (record.status !== 'in-flight' && record.status !== 'completed')) return undefined;",
    "    return record;",
    "  } catch (error) {",
    "    if (error?.code === 'ENOENT' || error instanceof SyntaxError) return undefined;",
    "    throw error;",
    "  }",
    "}",
    "async function writeInvocationRecord(recordKey, record) {",
    "  const { recordDirectory, recordPath } = invocationRecordPaths(recordKey);",
    "  const temporaryPath = join(recordDirectory, `record.${invocationProcessId.replaceAll(':', '-')}.tmp`);",
    "  const { rename, writeFile } = await import('node:fs/promises');",
    "  await writeFile(temporaryPath, JSON.stringify(record), 'utf8');",
    "  await rename(temporaryPath, recordPath);",
    "}",
    "async function acquireInvocationLock(recordKey) {",
    "  const { lockDirectory } = invocationRecordPaths(recordKey);",
    "  const { mkdir, writeFile } = await import('node:fs/promises');",
    "  try {",
    "    await mkdir(lockDirectory);",
    "    await writeFile(join(lockDirectory, 'owner'), invocationProcessId, 'utf8');",
    "    return true;",
    "  } catch (error) {",
    "    if (error?.code === 'EEXIST') return false;",
    "    throw error;",
    "  }",
    "}",
    "async function releaseInvocationLock(recordKey) {",
    "  const { lockDirectory } = invocationRecordPaths(recordKey);",
    "  const { readFile, rm } = await import('node:fs/promises');",
    "  try {",
    "    if (await readFile(join(lockDirectory, 'owner'), 'utf8') !== invocationProcessId) return;",
    "    await rm(lockDirectory, { recursive: true, force: true });",
    "  } catch (error) {",
    "    if (error?.code !== 'ENOENT') throw error;",
    "  }",
    "}",
    "async function publishInvocationRecord(recordKey, record) {",
    "  const { recordDirectory } = invocationRecordPaths(recordKey);",
    "  const temporaryDirectory = join(CONFIG.providerInvocationStatePath, `.${recordKey}.${invocationProcessId.replaceAll(':', '-')}.tmp`);",
    "  const { mkdir, rename, rm, writeFile } = await import('node:fs/promises');",
    "  await mkdir(temporaryDirectory);",
    "  try {",
    "    await writeFile(join(temporaryDirectory, 'record.json'), JSON.stringify(record), 'utf8');",
    "    await rename(temporaryDirectory, recordDirectory);",
    "  } catch (error) {",
    "    await rm(temporaryDirectory, { recursive: true, force: true });",
    "    throw error;",
    "  }",
    "}",
    "async function compactCompletedInvocationRecords() {",
    "  const statePath = CONFIG.providerInvocationStatePath;",
    "  if (!statePath) return;",
    "  const { readdir, rename, rm } = await import('node:fs/promises');",
    "  let names;",
    "  try { names = await readdir(statePath); } catch (error) { if (error?.code === 'ENOENT') return; throw error; }",
    "  const completed = [];",
    "  for (const name of names) {",
    "    if (!/^[a-f0-9]{64}$/.test(name)) continue;",
    "    const record = await readInvocationRecord(name);",
    "    if (record?.status === 'completed' && Number.isFinite(record.completedAt)) completed.push({ name, completedAt: record.completedAt });",
    "  }",
    "  completed.sort((left, right) => right.completedAt - left.completedAt);",
    "  const cutoff = Date.now() - invocationCompletedRetentionMs;",
    "  for (const record of completed.filter((entry, index) => index >= invocationCompletedRetentionCount || entry.completedAt < cutoff)) {",
    "    if (!(await acquireInvocationLock(record.name))) continue;",
    "    const paths = invocationRecordPaths(record.name);",
    "    const retiredDirectory = join(statePath, `.${record.name}.${invocationProcessId.replaceAll(':', '-')}.retired`);",
    "    try {",
    "      if ((await readInvocationRecord(record.name))?.status !== 'completed') continue;",
    "      await rename(paths.recordDirectory, retiredDirectory);",
    "      await rm(retiredDirectory, { recursive: true, force: true });",
    "    } catch (error) {",
    "      if (error?.code !== 'ENOENT') throw error;",
    "    } finally {",
    "      await releaseInvocationLock(record.name);",
    "    }",
    "  }",
    "}",
    "function withInvocationStateLock(task) {",
    "  const previous = invocationStateQueue;",
    "  let release;",
    "  invocationStateQueue = new Promise((resolve) => { release = resolve; });",
    "  return previous.then(task).finally(() => release());",
    "}",
    "function scopedMcpInvocationId(prefix, value) {",
    "  const sessionId = String(CONFIG.providerSessionId || CONFIG.threadId);",
    "  const identity = `${prefix}:${sessionId}:${value}`;",
    "  return identity.length <= 200 ? identity : `${prefix}:${createHash('sha256').update(identity).digest('hex')}`;",
    "}",
    "async function resolveMcpInvocationId(request) {",
    "  const metadataId = validInvocationMetadataId(request);",
    "  const requestId = request.id;",
    "  if (!metadataId && ((typeof requestId !== 'string' && typeof requestId !== 'number') || (typeof requestId === 'number' && !Number.isSafeInteger(requestId)))) throw new Error(`${ERROR_CODE}: tools/call must include a standard JSON-RPC request id. No work was dispatched.`);",
    "  const typedIdentity = metadataId ? undefined : invocationStateKey(requestId);",
    "  const identity = metadataId ? scopedMcpInvocationId('mcp-meta', metadataId) : scopedMcpInvocationId('mcp-request', typedIdentity);",
    "  if (!CONFIG.providerInvocationStatePath) {",
    "    if (!metadataId && !/^[\\x21-\\x7e]{1,200}$/.test(String(requestId))) throw new Error(`${ERROR_CODE}: the JSON-RPC request id is not a bounded stable identity. No work was dispatched.`);",
    "    return identity;",
    "  }",
    "  return withInvocationStateLock(async () => {",
    "    const recordKey = invocationRecordKey(request, identity);",
    "    const durableIdentity = metadataId ? identity : scopedMcpInvocationId('mcp-digest', recordKey);",
    "    const storedIdentity = metadataId ? createHash('sha256').update(durableIdentity).digest('hex') : durableIdentity;",
    "    const { mkdir } = await import('node:fs/promises');",
    "    await mkdir(CONFIG.providerInvocationStatePath, { recursive: true });",
    "    if (!(await acquireInvocationLock(recordKey))) throw new Error(`${ERROR_CODE}_REPLAY_AMBIGUOUS: the provider retried work while an earlier invocation may still be active. No work was dispatched.`);",
    "    const previous = await readInvocationRecord(recordKey);",
    "    if (previous?.status === 'completed') return durableIdentity;",
    "    if (previous) { await releaseInvocationLock(recordKey); throw new Error(`${ERROR_CODE}_REPLAY_AMBIGUOUS: the provider retried work after bridge restart before its outcome was confirmed. No work was dispatched.`); }",
    "    const now = Date.now();",
    "    try {",
    "      await publishInvocationRecord(recordKey, { formatVersion: invocationStateFormatVersion, requestDigest: recordKey, identity: storedIdentity, status: 'in-flight', createdAt: now, updatedAt: now });",
    "      return durableIdentity;",
    "    } catch (error) {",
    "      await releaseInvocationLock(recordKey);",
    "      if (error?.code === 'EEXIST' || error?.code === 'ENOTEMPTY') throw new Error(`${ERROR_CODE}_REPLAY_AMBIGUOUS: durable invocation state already exists. No work was dispatched.`);",
    "      throw error;",
    "    }",
    "  });",
    "}",
    "async function completeMcpInvocation(request) {",
    "  if (!CONFIG.providerInvocationStatePath || (!validInvocationMetadataId(request) && typeof request.id !== 'string' && typeof request.id !== 'number')) return;",
    "  return withInvocationStateLock(async () => {",
    "    const metadataId = validInvocationMetadataId(request);",
    "    const identity = metadataId ? scopedMcpInvocationId('mcp-meta', metadataId) : scopedMcpInvocationId('mcp-request', invocationStateKey(request.id));",
    "    const recordKey = invocationRecordKey(request, identity);",
    "    const previous = await readInvocationRecord(recordKey);",
    "    if (!previous) return;",
    "    const now = Date.now();",
    "    try {",
    "      await writeInvocationRecord(recordKey, { ...previous, status: 'completed', updatedAt: now, completedAt: now });",
    "    } finally {",
    "      await releaseInvocationLock(recordKey);",
    "    }",
    "    await compactCompletedInvocationRecords();",
    "  });",
    "}",
  ]
    .join("\n")
    .replaceAll("${ERROR_CODE}", errorCode);
}
