import type { OrchestrationEvent } from "@bigbud/contracts";

import { canReplaceThreadTitle } from "../orchestration/Layers/ProviderCommandReactorHelpers.ts";

const lockedThreadIds = new Set<string>();
const titleVersions = new Map<string, number>();

export function lockThreadTitle(threadId: string): number {
  lockedThreadIds.add(threadId);
  const nextVersion = (titleVersions.get(threadId) ?? 0) + 1;
  titleVersions.set(threadId, nextVersion);
  return nextVersion;
}

export function isThreadTitleLocked(threadId: string): boolean {
  return lockedThreadIds.has(threadId);
}

export function getThreadTitleVersion(threadId: string): number {
  return titleVersions.get(threadId) ?? 0;
}

export function isAutoGeneratedTitleCommand(commandId: string): boolean {
  const normalized = commandId.trim();
  return (
    normalized.includes("thread-title-rename") ||
    normalized.includes("thread-title-seed") ||
    normalized.includes("bootstrap-thread-meta-update")
  );
}

export function isProviderThreadMetadataTitleCommand(commandId: string): boolean {
  return commandId.trim().includes("thread-meta-update");
}

export function shouldAllowAutoTitleReplace(input: {
  readonly threadId: string;
  readonly currentTitle: string;
  readonly titleSeed?: string;
}): boolean {
  if (isThreadTitleLocked(input.threadId)) {
    return false;
  }
  return canReplaceThreadTitle(input.currentTitle, input.titleSeed);
}

export function noteThreadTitleCommand(input: {
  readonly threadId: string;
  readonly commandId: string | null;
  readonly title?: string;
}): void {
  if (input.title === undefined || input.title.trim().length === 0) {
    return;
  }
  if (input.commandId === null) {
    return;
  }
  if (isAutoGeneratedTitleCommand(input.commandId)) {
    return;
  }
  if (isProviderThreadMetadataTitleCommand(input.commandId)) {
    return;
  }
  lockThreadTitle(input.threadId);
}

export function rehydrateThreadTitleLocks(events: ReadonlyArray<OrchestrationEvent>): void {
  lockedThreadIds.clear();
  titleVersions.clear();
  for (const event of events) {
    if (event.type !== "thread.meta-updated" || event.payload.title === undefined) {
      continue;
    }
    noteThreadTitleCommand({
      threadId: event.payload.threadId,
      commandId: event.commandId,
      title: event.payload.title,
    });
  }
}

export function resetThreadTitleLockForTests(): void {
  rehydrateThreadTitleLocks([]);
}
